apiVersion: v1
appVersion: v1.91.3
description: Victoria Metrics Agent - collects metrics from various sources and stores
  them to VictoriaMetrics
name: victoria-metrics-agent
sources:
- https://github.com/VictoriaMetrics/helm-charts
version: 0.8.41
