{{- $vmConfig := index .Values "victoria-metrics-distributed" -}}
{{ if and (.Values.global.backend.enabled) ($vmConfig.pvcAnnotationsJob.vmstorage.enabled) }}
{{- $vmConfig := index .Values "victoria-metrics-distributed" -}}
{{- if and $vmConfig.availabilityZones $vmConfig.zoneTpl.vmcluster.spec.vmstorage -}}
{{- $replicaCount := $vmConfig.zoneTpl.vmcluster.spec.vmstorage.replicaCount | default 3 -}}
{{- $nameOverride := $vmConfig.nameOverride | default "victoriametrics" -}}
{{- range $zoneIndex, $zone := $vmConfig.availabilityZones -}}
{{- $zoneName := $zone.name -}}
{{- range $replicaIndex := until ($replicaCount | int) -}}
{{- $hookJobName := printf "vmstorage-pvc-hook-%s-%d" $zoneName $replicaIndex -}}
{{- $pvcName := printf "vmstorage-db-vmstorage-vmcluster-%s-%d" $zoneName $replicaIndex -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $hookJobName }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    helm.sh/hook-weight: "0"
    helm.sh/hook: "pre-upgrade"
    helm.sh/hook-delete-policy: "before-hook-creation"  
  labels:
    app.kubernetes.io/component: vmstorage-pvc-hook
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app.kubernetes.io/component: vmstorage-pvc-hook
    spec:
      restartPolicy: Never
      {{- if $.Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml $.Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "statefulset-modifier.fullname" $ }}
      containers:
        - name: kubectl-pvc-patcher
          image: {{ tpl $vmConfig.pvcAnnotationsJob.image $ }}
          command:
            - sh
            - -c
            - |
              set -e
              echo "Patching PVC: {{ $pvcName }} for zone: {{ $zoneName }}, replica: {{ $replicaIndex }}"

              # Patch the PVC with custom annotations
              kubectl annotate pvc {{ $pvcName }} --namespace={{ $.Release.Namespace }} {{- range $key, $value := $vmConfig.pvcAnnotationsJob.vmstorage.annotations }} {{ $key | quote }}={{ $value | quote }}{{- end }} --overwrite || echo "patching PVC failed" && exit 0
              
              echo "Successfully patched PVC {{ $pvcName }}"
---              
{{- end }}
{{- end }}
{{- end }}
{{- end }}
