{{- if .Values.upgradeCRDs }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cert-manager-crds.fullname" . }}
  annotations:
  {{- include "cert-manager-crds.rbac.annotations" $ | nindent 4 }}
rules:
  - apiGroups: 
      - "apiextensions.k8s.io"
    resources: 
      - "customresourcedefinitions"
    verbs: 
      - create
      - patch
      - update
      - get
      - list
{{- end }}