{{- if .Values.upgradeCRDs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cert-manager-crds.fullname" . }}
  annotations:
  {{- include "cert-manager-crds.job.annotations" . | nindent 4 }}
data:
{{ (.Files.Glob "crds/crds.yaml").AsConfig | indent 2 }}
{{- end }}
