{{ if and .Values.global.metricsAggregator.enabled .Values.global.backend.enabled }}
{{- $sensorValues := deepCopy .Values.metricsAggregator -}}
{{- $sensorValues = mergeOverwrite $sensorValues (default (dict) .Values.global.metricsAggregator) -}}
kind: Service
apiVersion: v1
metadata:
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if $sensorValues.additionalAnnotations }}
{{ toYaml $sensorValues.additionalAnnotations | indent 4 }}
    {{- end }}
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    app: metrics-aggregator
    app.kubernetes.io/name: metrics-aggregator
    {{- if $sensorValues.additionalLabels }}
{{ toYaml $sensorValues.additionalLabels | indent 4 }}
    {{- end }}
  name: {{ include "metrics-aggregator.fullname" . }}-headless
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  selector:
    app: metrics-aggregator
  ports: {{ include "groundcover.sensor.service.ingestion-ports" (merge (dict "sensorValues" $sensorValues) .) | nindent 2 }}
{{ end -}}
