apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "shepherd.name" . }}
  labels:
    {{ with .Values.global.groundcoverLabels }} 
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app: shepherd
    {{- include "shepherd.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: shepherd
      {{- include "shepherd.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        groundcover.com/scrape: "true"
        groundcover.com/port: "{{ .Values.config.httpPort }}"
        groundcover.com/path: "/data"
        groundcover.com/scheme: {{ template "shepherd_scheme" . }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.config.httpPort }}"
        prometheus.io/path: "/metrics"
        prometheus.io/scheme: {{ template "shepherd_scheme" . }}
        checksum/config: {{ printf "%s" .Values.config | sha256sum -}}
    {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{ with .Values.global.groundcoverLabels }} 
        {{- toYaml . | nindent 8 }}
        {{- end }}
        app: shepherd
        {{- include "shepherd.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "shepherd.name" . }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ tpl .Values.image.repository . }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts: 
            - name: config
              mountPath: /config
            - name: certificate
              mountPath: /var/groundcover/server
              readOnly: true
          ports:
            - name: http-metrics
              containerPort: {{ .Values.config.httpPort }}
              protocol: TCP
            - name: grpc-shepherd
              containerPort: {{ .Values.config.grpcPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http-metrics
              scheme: {{ include "shepherd_scheme" . | upper }}
          readinessProbe:
            httpGet:
              path: /health
              port: http-metrics
              scheme: {{ include "shepherd_scheme" . | upper }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "shepherd.name" . }}-config
        - name: certificate
          secret:
            secretName: {{ template "shepherd_secrets_certificate" . }}
            defaultMode: 416 # 0640 permissions
