annotations:
  category: Database
  images: |
    - name: clickhouse
      image: docker.io/bitnami/clickhouse:23.12.2-debian-11-r0
    - name: os-shell
      image: docker.io/bitnami/os-shell:11-debian-11-r93
    - name: zookeeper
      image: docker.io/bitnami/zookeeper:3.8.3-debian-11-r4
  licenses: Apache-2.0
apiVersion: v2
appVersion: 23.12.2
dependencies:
- condition: zookeeper.enabled
  name: zookeeper
  repository: oci://registry-1.docker.io/bitnamicharts
  version: 12.x.x
- name: common
  repository: oci://registry-1.docker.io/bitnamicharts
  tags:
  - bitnami-common
  version: 2.x.x
description: ClickHouse is an open-source column-oriented OLAP database management
  system. Use it to boost your database performance while providing linear scalability
  and hardware efficiency.
home: https://bitnami.com
icon: https://bitnami.com/assets/stacks/clickhouse/img/clickhouse-stack-220x234.png
keywords:
- database
- sharding
maintainers:
- name: VMware, Inc.
  url: https://github.com/bitnami/charts
name: clickhouse
sources:
- https://github.com/bitnami/charts/tree/main/bitnami/clickhouse
version: 4.2.0
