{{ if .Values.global.integrations.agent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    {{- if .Values.integrationsAgent.additionalLabels }}
{{ toYaml .Values.integrationsAgent.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.integrationsAgent.serviceAccount }}
    {{- if .Values.integrationsAgent.serviceAccount.annotations }}
{{ toYaml .Values.integrationsAgent.serviceAccount.annotations | indent 4 }}
    {{- end }}
    {{- end }}
    {{- if .Values.integrationsAgent.additionalAnnotations }}
{{ toYaml .Values.integrationsAgent.additionalAnnotations | indent 4 }}
    {{- end }}
  name: integrations-agent
  namespace: {{ .Release.Namespace }}
{{ end }}
