{{ if .Values.agent.enabled }}
apiVersion: v1
data:
  promtail.yaml: |-
    client:
      tls_config:
        insecure_skip_verify: true
      backoff_config:
        max_period: 5m
        max_retries: 10
        min_period: 500ms
      batchsize: 1048576
      batchwait: 5s
      external_labels:
        clusterId: ${GC_CLUSTERID}
      timeout: 10s
      groundcover_pager_host: 127.0.0.1
      groundcover_pager_port: 9119
      groundcover_pager_timeout: 2m
      groundcover_time_travel: -20s
    positions:
      filename: /run/promtail/positions.yaml
    server:
      http_listen_port: 3101
      log_level: warn
    target_config:
      sync_period: 10s
    scrape_configs:
    - job_name: kubernetes-pods-name
      pipeline_stages:  
      - docker: {}
      - match:
          selector: '{container=~".+"}'
          stages:
          - regex:
              expression: '.*(?P<level>(?i)FATAL|PANIC|ERROR|WARNING|WARN|INFO|DEBUG|TRACE).*' 
          - labels:
              level:
      - labeldrop:
        - filename
      - labeldrop:
        - controller_uid
      - labeldrop:
        - pod_template_hash
      - labeldrop:
        - controller_revision_hash
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_label_name
        target_label: workload
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - action: labelmap
        regex: __meta_kubernetes_pod_label_(.+)
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/*$1/*.log
        separator: /
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        target_label: __path__
kind: ConfigMap
metadata:
  labels:
    {{ with .Values.global.groundcoverLabels }} 
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.agent.additionalLabels }}
{{ toYaml .Values.agent.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.origin.tag }}
    {{- if .Values.agent.additionalAnnotations }}
{{ toYaml .Values.agent.additionalAnnotations | indent 4 }}
    {{- end }}
  name: promtail-config
  namespace: {{ .Release.Namespace }}
{{ end -}}