{{- if and .Values.keeper.enabled .Values.keeper.pdb.enabled }}
{{ include "clickhouseKeeper.pdb" (dict "root" . "values" .Values.keeper "valuesPath" "keeper" "nameSuffix" "clickhouse-keeper") }}
{{- end }}
