{{ if .Values.backend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{ with .Values.global.groundcoverLabels }} 
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.dbManager.additionalLabels }}
{{ toYaml .Values.dbManager.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.dbManager.additionalAnnotations }}
{{ toYaml .Values.dbManager.additionalAnnotations | indent 4 }}
    {{- end }}
  name: db-manager
  namespace: {{ .Release.Namespace }}
{{ end -}}
