{{ if .Values.global.backend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{ with .Values.global.groundcoverLabels }} 
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.dbManager.additionalLabels }}
{{ toYaml .Values.dbManager.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- $annotations := (merge .Values.dbManager.additionalAnnotations .Values.dbManager.serviceAccount.annotations) -}}
    {{- if $annotations }}
{{ toYaml $annotations | indent 4 }}
    {{- end }}
  name: {{ default "db-manager" .Values.dbManager.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
{{ end -}}