apiVersion: v2
appVersion: 1.4.42
dependencies:
- condition: onprem.enabled
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.7.2
- condition: onprem.enabled
  name: grafana
  repository: https://grafana.github.io/helm-charts
  version: 6.58.6
description: groundcover's router helm chart
name: router
type: application
version: 1.4.42
