apiVersion: v2
appVersion: 0.1.0
dependencies:
- name: kong
  repository: https://charts.konghq.com
  version: 2.20.0
description: A Helm chart for Kubernetes
name: incloud-ingress
type: application
version: 0.1.0
