{{ if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: opentelemetry-collector-certificate
  labels:
    {{ with .Values.global.groundcoverLabels }} 
      {{- toYaml . | nindent 4 }}
    {{- end }}
{{ $ca := genCA (include "opentelemetry-collector.fullname" .) 1826 -}}
stringData:
  tls.key: {{ $ca.Key  | quote }}
  tls.crt: {{ $ca.Cert | quote }}
{{- end }}
