{{- if and .Values.onprem.enabled (.Capabilities.APIVersions.Has "security.openshift.io/v1") }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ printf "%s-scc" (include "grafana.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grafana
  {{- include "router.labels" . | nindent 4 }}
  annotations: {}
rules:
  - apiGroups:
      - security.openshift.io
    resources:
      - securitycontextconstraints
    verbs:
      - use
    resourceNames:
      - nonroot-v2
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ printf "%s-scc" (include "grafana.fullname" .) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: grafana
  {{- include "router.labels" . | nindent 4 }}
  annotations: {}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ printf "%s-scc" (include "grafana.fullname" .) }}
subjects:
  - kind: ServiceAccount
    namespace: {{ .Release.Namespace }}
    name: {{ include "grafana.serviceAccountName" . }}
{{ end -}}
