{{ if .Values.global.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.portal.additionalAnnotations }}
{{ toYaml .Values.portal.additionalAnnotations | indent 4 }}
    {{- end }}
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    app: {{ include "portal.fullname" . }}
    app.kubernetes.io/name: {{ include "portal.fullname" . }}
    {{- if .Values.portal.additionalLabels }}
{{ toYaml .Values.portal.additionalLabels | indent 4 }}
    {{- end }}
  name: {{ include "portal.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: grpc-portal
    port: 5555
    protocol: TCP
    targetPort: grpc-portal
  - name: http
    port: 9999
    protocol: TCP
    targetPort: portal-http

  selector:
    app: {{ include "portal.fullname" . }}
  type: ClusterIP
{{ end -}}
