{{ if .Values.backend.enabled }}
apiVersion: v1
data:
  config.yaml: |-
{{ if eq .Values.router.mode "cloud" }}

    LogLevel: 4

    Reverse: true
    startuptimeout: 1m0s

    ClusterId: {{ template "groundcover.clusterId" . }}
    MultipleClusterIds: 
    {{- with .Values.multipleClusterIds }}{{ toYaml . | nindent 6 }}{{- end }}  
    GroundcoverVersion: "OVERRIDEN"

    Incluster: true
    Namespace: {{ .Release.Namespace }}
    
    Router:
      Host: "{{ .Values.saas.host }}"
      Port: "{{ .Values.saas.port }}"
      Token: "OVERRIDEN"
      WebsocketScheme: "{{ .Values.saas.scheme }}"
      TLSSkipVerify: "{{ .Values.saas.tls_skip_verify }}"
      ExtraHeaders:
    {{- if .Values.installationId }}
        - Key: X-Portal-InstallationId
          Value: {{ .Values.installationId }}
    {{- end }}

    DirectModeGRPCPort: "5555"

    DB:
      Host: "groundcover-tsdb"
      Port: "5432"
      Name: "groundcover"
      User: "postgres"
      Pass: "password"
      Timeout: 150s
      Interval: 5s

    VictoriaMetrics:
      URL: "http://groundcover-victoria-metrics:8428"

    Loki:
      Host: "groundcover-loki"
      Port: 3100
{{ else }}
    LogLevel: 4

    Reverse: false
    startuptimeout: 1m0s

    ClusterId: {{ template "groundcover.clusterId" . }}
    {{- with .Values.multipleClusterIds }}
      {{ toYaml . | nindent 6 }}
    {{- end }}  
    GroundcoverVersion: "OVERRIDEN"

    Incluster: true
    Namespace: {{ .Release.Namespace }}

    Router:
      Host: "router"
      Port: "8080"
      Token: "not-available"
      WebsocketScheme: "wss"
      TLSSkipVerify: "false"
      ExtraHeaders:
      {{- if .Values.installationId }}
        - Key: X-Portal-InstallationId
          Value: {{ .Values.installationId }}
      {{- end }}

    DirectModeGRPCPort: "5555"

    DB:
      Host: "groundcover-tsdb"
      Port: "5432"
      Name: "groundcover"
      User: "postgres"
      Pass: "password"
      Timeout: 150s
      Interval: 5s

    VictoriaMetrics:
      URL: "http://groundcover-victoria-metrics:8428"

    Loki:
      Host: "groundcover-loki"
      Port: 3100
{{ end }}
kind: ConfigMap
metadata:
  labels:
    {{ with .Values.global.groundcoverLabels }} 
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.portal.additionalLabels }}
{{ toYaml .Values.portal.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.portal.additionalAnnotations }}
{{ toYaml .Values.portal.additionalAnnotations | indent 4 }}
    {{- end }}
  name: portal-config
  namespace: {{ .Release.Namespace }}
{{ end -}}
