{{ if .Values.agent.enabled }}
apiVersion: v1
data:
  config.yaml: |
    LogLevel: 4
    resourceconntimeout: 1m0s
    concurrency: 10
    productchansize: 20480
    k8sloadtimeout: 2m0s
    resyncDuration: 1h
    groundcoverVersion: ""
    podsResyncDuration: 15m
    unavailableDeploymentPollInterval: 10s
    summarizerActiveTtl: 180s
    pushsummaries: true
    productmetricsflushmintotalcounter:
      deployment_event: 1
      unavailable_deployment: 1

    deploymenteventhandler:
      samplesthreshold: 100
      issuesthreshold: 100
      interval: 60s
      samplingmode: 0 # DontSample

    unavailabledeploymenthandler:
      samplesthreshold: 100
      issuesthreshold: 100
      interval: 60s
      samplingmode: 1 # DefaultSample
    
    VictoriaMetrics:
      url: {{ include "metrics-ingester.base.http.url" . }}
      TLSSkipVerify: true

    dataRetention: {{ .Values.agent.alligator.dataRetention }}
    
    runningNamespace: ""
    clusterId: {{ .Values.clusterId }}
    region: {{ .Values.region }}
    shouldDropRunningNamespaces: {{ .Values.shouldDropRunningNamespaces }}
    tracesNamespaceFilters: {{ toYaml .Values.tracesNamespaceFilters | nindent 6 }}
    tracesWorkloadFilters: {{ toYaml .Values.tracesWorkloadFilters | nindent 6 }}
    commitHashKeyName: {{ .Values.commitHashKeyName }}
    repositoryUrlKeyName: {{ .Values.repositoryUrlKeyName }}
    otlp:
      endpoint: {{ include "opentelemetry-collector.otlp.grpc.url" . }}
      enableTLS: {{ .Values.global.otlp.tls.enabled }}
      writeTimeout: 10s
      batchSize: 350
      flushInterval: 1s
kind: ConfigMap
metadata:
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    {{- if .Values.portal.additionalLabels }}
{{ toYaml .Values.portal.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.portal.additionalAnnotations }}
{{ toYaml .Values.portal.additionalAnnotations | indent 4 }}
    {{- end }}
  name: k8s-watcher-config
  namespace: {{ .Release.Namespace }}
{{ end }}