apiVersion: v1
data:
  config.yaml: |
    LogLevel: 4
    resourceconntimeout: 1m0s

    VictoriaMetrics:
      Host: "groundcover-vmagent"
      Port: 8429

    Promscale:
      host: groundcover-promscale-connector
      port: 9202

    deploymenteventhandler:
      samplesthreshold: 100
      issuesthreshold: 100
      interval: 60s
      shouldsample: false

    dataRetention: {{ .Values.agent.alligator.dataRetention }}
    
    runningNamespace: ""
    clusterId: {{ .Values.clusterId }}
    region: {{ .Values.region }}
    shouldDropRunningNamespaces: {{ .Values.shouldDropRunningNamespaces }}
    filteredNamespaces: {{ toYaml .Values.filteredNamespaces | nindent 6 }}
kind: ConfigMap
metadata:
  labels:
    {{- if .Values.portal.additionalLabels }}
{{ toYaml .Values.portal.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ .Values.origin.tag }}
    {{- if .Values.portal.additionalAnnotations }}
{{ toYaml .Values.portal.additionalAnnotations | indent 4 }}
    {{- end }}
  name: k8s-watcher-config
  namespace: {{ .Release.Namespace }}
