{{ if .Values.agent.enabled }}
apiVersion: v1
data:
  config.yaml: |
    LogLevel: 4
    resourceconntimeout: 1m0s
    concurrency: 10
    productchansize: 20480

    VictoriaMetrics:
      URL: "{{ template "vmagent.url" . }}"
      TLSSkipVerify: false

    Promscale:
      url: "{{ template "promscale.otelURL" . }}"
      tls: "true"
      tableWriterBatchMaxSize: 1000
      tableWriterBatchInterval: 1s
      tableWriterBatchWriteTimeout: 1s

    deploymenteventhandler:
      samplesthreshold: 100
      issuesthreshold: 100
      interval: 60s
      shouldsample: false

    dataRetention: {{ .Values.agent.alligator.dataRetention }}
    
    runningNamespace: ""
    clusterId: {{ .Values.clusterId }}
    region: {{ .Values.region }}
    shouldDropRunningNamespaces: {{ .Values.shouldDropRunningNamespaces }}
    filteredNamespaces: {{ toYaml .Values.filteredNamespaces | nindent 6 }}
kind: ConfigMap
metadata:
  labels:
    {{ with .Values.global.groundcoverLabels }} 
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.portal.additionalLabels }}
{{ toYaml .Values.portal.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ .Values.origin.tag }}
    {{- if .Values.portal.additionalAnnotations }}
{{ toYaml .Values.portal.additionalAnnotations | indent 4 }}
    {{- end }}
  name: k8s-watcher-config
  namespace: {{ .Release.Namespace }}
{{ end }}