{{ if .Values.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "shepherd.name" . }}-certificate
  labels:
    {{ with .Values.global.groundcoverLabels }} 
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app: shepherd
type: kubernetes.io/tls
{{ $ca := genCA (include "shepherd.name" .) 1826 -}}
stringData:
  tls.crt: {{ $ca.Cert | quote }}
  tls.key: {{ $ca.Key  | quote }}
{{- end }}
