{{ if .Values.agent.enabled }}
apiVersion: v1
data:
  config.yaml: |-
    startuptimeout: 120s
    concurrency: 1000
    productchansize: 1000
    pushsummaries: true
    productmetricsflushmintotalcounter:
      http: 2
      redis: 2
      sql: 2
      kafka: 2
      dns: 2
      conn_stats: 2
      tcp_stats: 2
      node_info: 2
      container_crash: 1
      container_info: 1
      pvc_info: 2
      container_state: 1
    tracyEnabled: {{ template "agent.tracy.enabled" . }}
    tracy:
      address: "ipc:///comm/tracy.data"
      timeout: 120s
      interval: 5s

    httphandler:
      samplesthreshold: 10
      issuesthreshold: 10
      samplingmode: 1 # DefaultSample
      interval: 30s
      summarizerActiveTtl: 180s

    redishandler:
      samplesthreshold: 10
      issuesthreshold: 10
      samplingmode: 1 # DefaultSample
      interval: 30s
      summarizerActiveTtl: 180s  

    sqlhandler:
      samplesthreshold: 10
      issuesthreshold: 10
      samplingmode: 1 # DefaultSample
      interval: 30s
      summarizerActiveTtl: 180s

    kafkahandler:
      samplesthreshold: 10
      issuesthreshold: 10
      samplingmode: 1 # DefaultSample
      interval: 30s
      summarizerActiveTtl: 180s

    dnshandler:
      samplesthreshold: 10
      issuesthreshold: 10
      samplingmode: 1 # DefaultSample
      interval: 30s
      summarizerActiveTtl: 180s

    connStatsHandler:
      samplesthreshold: 10
      issuesthreshold: 10
      samplingmode: 0 # DontSample
      interval: 30s
      summarizerActiveTtl: 180s

    tcpStatsHandler:
      samplesthreshold: 10
      issuesthreshold: 10
      samplingmode: 0 # DontSample
      interval: 30s
      summarizerActiveTtl: 180s

    containerInfoHandler:
      samplesthreshold: 10
      issuesthreshold: 10
      samplingmode: 1 # DefaultSample
      interval: 30s
      summarizerActiveTtl: 180s

    containerStateHandler:
      samplesthreshold: 10
      issuesthreshold: 10
      samplingmode: 0 # DontSample
      interval: 30s
      summarizerActiveTtl: 180s
    
    nodeinfohandler:
      samplesthreshold: 20
      issuesthreshold: 20
      samplingmode: 0 # DontSample
      interval: 1m0s
      summarizerActiveTtl: 180s
    
    timeseriesstorage:
      url: {{ include "metrics-ingester.base.http.url" . }}
      tlsskipverify: true

    containercrashhandler:
      samplesthreshold: 20
      issuesthreshold: 20
      samplingmode: 1 # DefaultSample
      interval: 30s
      summarizerActiveTtl: 180s

    pvcinfohandler:
      samplesthreshold: 20
      issuesthreshold: 20
      samplingmode: 0 # DontSample
      interval: 1m0s
      summarizerActiveTtl: 180s

    pidcache:
      expiration: 5m
      purge: 20s

    cluster:
      maxhosts: 10000
      maxchildrens: 40

    storage:
      timeout: 5s

    loglevel: 4 # INFO

    isk8s: true
    hostmodeconfigpath: "/config/instance_metadata.yaml"

    allowedportspercontainer: 20
    kubeletmetricsfetchinterval: 15s

    globallimiter:
      maxqueue: 10
      ageout: 100ms
      sampleeverything: false

    obfuscateData: {{ .Values.agent.alligator.obfuscateData }}
    dataRetention: {{ .Values.agent.alligator.dataRetention }}
    watchOnlyLocalNode: {{ .Values.agent.alligator.watchOnlyLocalNode }}
    floraEnabled: {{ ne .Values.mode "legacy" }}
    runningNamespace: ""
    shouldDropRunningNamespaces: {{ .Values.shouldDropRunningNamespaces }}
    tracesNamespaceFilters: {{ toYaml .Values.tracesNamespaceFilters | nindent 6 }}
    tracesWorkloadFilters: {{ toYaml .Values.tracesWorkloadFilters | nindent 6 }}
    nodelabels: {{ toYaml .Values.agent.alligator.nodelabels | nindent 6 }}
    contentTypesToDrop: {{ toYaml .Values.agent.alligator.contentTypesToDrop | nindent 6 }}
    apmForwarder: 
      dataDogEnabled: {{ .Values.agent.alligator.apmForwarder.dataDogEnabled }}
      dataDogEndpoint: {{ include "opentelemetry-collector.datadogapm.http.url" . }}
      enableTLS: {{ eq (get (urlParse (include "opentelemetry-collector.datadogapm.http.url" .)) "scheme") "https" }}
      writeTimeout: 10s
    pprofAlligator:
      enabled: {{ include "telemetry.enabled" . }}
      interval: {{ .Values.agent.alligator.pprofAlligator.interval }}
      exponent: {{ .Values.agent.alligator.pprofAlligator.exponent }}
      cpuSamplingDuration: {{ .Values.agent.alligator.pprofAlligator.cpuSamplingDuration }}
      httpUploader:
        enabled: {{ eq .Values.agent.alligator.pprofAlligator.uploaderType "http" }}
        pushURL: {{ printf "%s/upload/pprof" (include "telemetry.metrics.base.url" .) }}
      pyroscopeUploader:
        enabled: {{ eq .Values.agent.alligator.pprofAlligator.uploaderType "pyroscope" }}
        pushURL: {{ include "telemetry.metrics.base.url" . }}

    clusterId: {{ .Values.clusterId }}
    region: {{ .Values.region }}

    k8sLogs:
      scraper:
        positionsFile: "/var/run/positions/positions.yaml"
        positionsSyncInterval: 10s
        targetSyncInterval: 10s
      clients:
      - name: "logs_client"
        enabled: true
        urlText: {{ include "opentelemetry-collector.loki.http.url" . }}
        useApiKey: true
        batchwait: 2500ms
        batchsize: 10485760
        client:
          tlsconfig:
            insecureSkipVerify: true
        backoffConfig:
          minBackoff: 500ms
          maxBackoff: 5m
          maxRetries: 10
        externalLabels:
          labelSet:
            cluster_id: {{ .Values.clusterId }}
            job: alligator
        timeout: 10s
        useRingBuffer: {{ .Values.storeIssuesLogsOnly }}
        filterRunningNamespace: true
        groundcoverTimeTravel: -20s
        logDropFilters: {{ toYaml .Values.logsDropFilters | nindent 10}}
        metricateLabels: false
    otlp:
      endpoint: {{ include "opentelemetry-collector.otlp.grpc.url" . }}
      enableTLS: {{ .Values.global.otlp.tls.enabled }}
      writeTimeout: 10s
      batchSize: 350
      flushInterval: 1s
kind: ConfigMap
metadata:
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    {{- if .Values.agent.additionalLabels }}
{{ toYaml .Values.agent.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.agent.additionalAnnotations }}
{{ toYaml .Values.agent.additionalAnnotations | indent 4 }}
    {{- end }}
  name: alligator-configuration
  namespace: {{ .Release.Namespace }}
{{ end }}
