{{ if .Values.global.agent.enabled }}
apiVersion: v1
data:
  config.yaml: |-
      job_name: kubernetes-pods-name
      pipeline_stages:  
      - labeldrop:
        - filename
      - labeldrop:
        - controller_uid
      - labeldrop:
        - pod_template_hash
      - labeldrop:
        - controller_revision_hash
      - labeldrop:
        - stream
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_uid
        target_label: pod_uid
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/${3}_${4}_${1}/${2}/*.log
        regex: "([^;]+);([^;]+);([^;]+);([^;]+)"
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        - __meta_kubernetes_namespace
        - __meta_kubernetes_pod_name
        target_label: __path__
kind: ConfigMap
metadata:
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    {{- if .Values.agent.additionalLabels }}
{{ toYaml .Values.agent.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.agent.additionalAnnotations }}
{{ toYaml .Values.agent.additionalAnnotations | indent 4 }}
    {{- end }}
  name: alligator-scrape-configuration
  namespace: {{ .Release.Namespace }}
{{ end }}
