apiVersion: v1
kind: ConfigMap
metadata:
  name: victoria-metrics-aggregation-config
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
data:
  aggregation_config.yaml: |
    - ignore_old_samples: true
      match: '{__name__=~"groundcover_.+_.+_counter|groundcover_unavailable_count|groundcover_network.+", node_name!=""}'
      without: [node_name]
      interval: 30s
      outputs: [total_prometheus]
      output_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: "(.+):.*"
        replacement: "$1"
    - match: '{__name__=~"^groundcover_.+latency_seconds$", node_name!=""}'
      without: [node_name]
      interval: 30s
      outputs: [avg]
      output_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: "(.+):.*"
        replacement: "$1"