{{- if .Values.backend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: victoria-metrics-single-config
  labels: 
    app.kubernetes.io/name: victoria-metrics-single
  {{- include "groundcover.labels" . | nindent 4 }}
data:
  relabel_config.yaml: |
    - action: drop
      source_labels:
        - __name__
      regex: "^groundcover_.+_.+_counter$"
    - action: replace
      source_labels:
        - __name__
      target_label: __name__
      regex: "^aggregated_(.+)"
      replacement: "$1"
{{- end }}
