{{ if .Values.enabled }}
apiVersion: v1
data:
  config.yaml: |
{{ tpl (toYaml .Values.configuration) . | nindent 6 }}
kind: ConfigMap
metadata:
  name: router-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.additionalLabels }}
{{ tpl (toYaml .Values.additionalLabels) . | indent 4 }}
    {{- end }}
  annotations:
      groundcover_version: {{ .Values.origin.tag }}
{{ end }}