{{ if and .Values.global.commHub.enabled (not .Values.commHub.encryption.existingSecret) (not .Values.commHub.encryption.key) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "comm-hub.encryptionSecretName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    app: comm-hub
    app.kubernetes.io/name: comm-hub
  annotations:
    helm.sh/resource-policy: "keep"
type: Opaque
stringData:
  {{ include "comm-hub.encryptionSecretKeyName" . }}: {{ include "comm-hub.encryptionKey" . | quote }}
{{ end }}