annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - add VMSingle support. See [this issue](https://github.com/VictoriaMetrics/helm-charts/issues/2090).
    - bump version of K8s stack to 0.41.0
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-distributed
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com
    - name: Changelog
      url: https://docs.victoriametrics.com/changelog
  artifacthub.io/operator: "true"
apiVersion: v2
appVersion: v1.114.0
dependencies:
- name: victoria-metrics-common
  repository: https://victoriametrics.github.io/helm-charts
  version: 0.0.*
- condition: victoria-metrics-k8s-stack.enabled
  name: victoria-metrics-k8s-stack
  repository: https://victoriametrics.github.io/helm-charts
  version: 0.41.*
description: A Helm chart for Running VMCluster on Multiple Availability Zones
home: https://github.com/VictoriaMetrics/helm-charts
keywords:
- victoriametrics
- operator
- monitoring
- kubernetes
- observability
- tsdb
- metrics
- metricsql
- timeseries
kubeVersion: '>=1.25.0-0'
name: victoria-metrics-distributed
sources:
- https://github.com/VictoriaMetrics/helm-charts
type: application
version: 0.11.0
