{{ if .Values.global.agent.enabled }}
{{- $sensorValues := deepCopy .Values.agent.sensor -}}
{{- $sensorValues = set $sensorValues "alligatorConfigurationExists" false -}}
{{- if .Values.agent.alligator -}}
{{ $sensorValues = mergeOverwrite $sensorValues .Values.agent.alligator }}
{{- $sensorValues = set $sensorValues "alligatorConfigurationExists" true -}}
{{- end -}}
{{- $sensorValues = set $sensorValues "serviceName" "sensor" -}}
apiVersion: v1
data:
  config.yaml: |-
{{ include "groundcover.sensor.config" (merge (dict "sensorValues" $sensorValues) .) | indent 4 }}
kind: ConfigMap
metadata:
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    {{- if .Values.agent.additionalLabels }}
{{ toYaml .Values.agent.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.agent.additionalAnnotations }}
{{ toYaml .Values.agent.additionalAnnotations | indent 4 }}
    {{- end }}
  name: sensor-configuration
  namespace: {{ .Release.Namespace }}
{{ end }}
