{{ if .Values.global.agent.enabled }}
apiVersion: v1
data:
  config.yaml: |-
    ottlRules:
      []
              
kind: ConfigMap
metadata:
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    {{- if .Values.agent.additionalLabels }}
{{ toYaml .Values.agent.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.agent.additionalAnnotations }}
{{ toYaml .Values.agent.additionalAnnotations | indent 4 }}
    {{- end }}
  name: sensor-dynamic-configuration
  namespace: {{ .Release.Namespace }}
{{ end }}