{{ if .Values.global.agent.enabled }}
apiVersion: v1
data:
  config.yaml: |-
    - job_name: kubernetes-logs
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: __host__
      - source_labels:
        - __meta_kubernetes_pod_node_name
        target_label: node_name
      - action: replace
        source_labels:
        - __meta_kubernetes_namespace
        target_label: namespace
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: pod
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_name
        target_label: instance
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_uid
        target_label: pod_uid
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_uid
        target_label: instance_id
      - action: replace
        source_labels:
        - __meta_kubernetes_pod_container_name
        target_label: container
      - replacement: /var/log/pods/${3}_${4}_${1}/${2}/*.log
        regex: "([^;]+);([^;]+);([^;]+);([^;]+)"
        source_labels:
        - __meta_kubernetes_pod_uid
        - __meta_kubernetes_pod_container_name
        - __meta_kubernetes_namespace
        - __meta_kubernetes_pod_name
        target_label: __path__
      - target_label: source_type
        replacement: "k8s"
    - job_name: docker-logs
      docker_sd_configs:
        - host: unix:///var/run/docker.sock
      relabel_configs:
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: container
      - source_labels: [__meta_docker_container_name]
        regex: '/(.*)'
        target_label: instance
      - source_labels: [__meta_docker_container_id]
        target_label: instance_id
      - target_label: source_type
        replacement: "docker"
kind: ConfigMap
metadata:
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    {{- if .Values.agent.additionalLabels }}
{{ toYaml .Values.agent.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.agent.additionalAnnotations }}
{{ toYaml .Values.agent.additionalAnnotations | indent 4 }}
    {{- end }}
  name: sensor-scrape-configuration
  namespace: {{ .Release.Namespace }}
{{ end }}