{{ if .Values.agent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{ with .Values.global.groundcoverLabels }} 
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.portal.additionalLabels }}
{{ toYaml .Values.portal.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.portal.additionalAnnotations }}
{{ toYaml .Values.portal.additionalAnnotations | indent 4 }}
    {{- end }}
  name: k8s-watcher
  namespace: {{ .Release.Namespace }}
{{ end }}
