{{ if .Values.global.agent.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    {{- if .Values.k8sWatcher.additionalLabels }}
{{ toYaml .Values.k8sWatcher.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.k8sWatcher.additionalAnnotations }}
{{ toYaml .Values.k8sWatcher.additionalAnnotations | indent 4 }}
    {{- end }}
  name: k8s-watcher
  namespace: {{ .Release.Namespace }}
{{ end }}
