{{ if and .Values.global.backend.enabled (index .Values "volume-expansion" "enabled") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "volume-expansion.fullname" . }}
  labels:
  {{- include "groundcover.labels" . | nindent 4 }}
  annotations:
  {{- include "volume-expansion.rbac.annotations" $ | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - "persistentvolumeclaims"
    verbs:
      - "get"
      - "patch"
  - apiGroups:
      - "apps"
    resources:
      - "statefulsets"
    verbs:
      - "get"
      - "list"
      - "patch"
      - "delete"
{{- end -}}
