{{ if and .Values.global.backend.enabled (index .Values "volume-expansion" "enabled") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "volume-expansion.fullname" . }}
  labels:
  {{- include "groundcover.labels" . | nindent 4 }}
  annotations:
  {{- include "volume-expansion.rbac.annotations" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "volume-expansion.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "volume-expansion.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end -}}
