{{ if and .Values.global.backend.enabled (index .Values "volume-expansion" "enabled") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "volume-expansion.fullname" . }}
  labels:
  {{- include "groundcover.labels" . | nindent 4 }}
  annotations:
  {{- include "volume-expansion.rbac.annotations" $ | nindent 4 }}
{{- end -}}
