apiVersion: v1
appVersion: v1.77.1
description: Victoria Metrics Single version - high-performance, cost-effective and
  scalable TSDB, long-term remote storage for Prometheus
name: victoria-metrics-single
version: 0.8.19
