{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "notification-center.labels" . | nindent 4 }}
  annotations:
    groundcover_version: {{ .Values.origin.tag }}
  name: notification-center
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: ingest
      port: 8081
      protocol: TCP
      targetPort: ingest
  selector:
    {{- include "notification-center.selectorLabels" . | nindent 4 }}
  type: ClusterIP
{{ end -}}
