{{ if and .Values.apiIngress.enabled .Values.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: router-api-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.additionalLabels }}
  {{ toYaml .Values.additionalLabels | indent 4 }}
  {{- end }}
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: {{ .Values.apiIngress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: router
                port:
                  number: 8080
{{ end }}