{{- if .Values.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: router
    {{- include "router.labels" . | nindent 4 }}
  annotations:
    groundcover_version: {{ .Values.origin.tag }}
  name: router
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: router
  template:
    metadata:
      labels:
        app: router
        app.kubernetes.io/name: router
      {{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | indent 8 }}
      {{- end }}
      annotations:
        groundcover_version: {{ .Values.origin.tag }}
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        checksum/router_config: {{ include (print $.Template.BasePath "/config/configMap.yaml") . | sha256sum }}
    spec:
      serviceAccountName: router
      {{- if .Values.onprem.enabled }}
      initContainers:
        - name: wait-for-db
          image: '{{ include "postgresql.image" . }}'
          env:
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: '{{ include "postgresql.secretName" . }}'
                  key: '{{ include "postgresql.adminPasswordKey" . }}'
          command:
            - /bin/sh
            - -c
          args:
            - |
              pg_isready \
                -U "postgres" \
                -d "dbname=postgres" \
                -h {{ splitList ":" (include "postgresql.base.url" .) | first }} \
                -p {{ splitList ":" (include "postgresql.base.url" .) | last }}
        - name: check-grafana-is-up   
          args:
          - while [ $(curl -skw '%{http_code}' http://{{ include "grafana.fullname" . }}/grafana/healthz
            -o /dev/null) -ne 200 ]; do echo 'Waiting for grafana...'; sleep 2; done; echo grafana is up
          command:
            - /bin/sh
            - -c
          image: '{{ printf "%s/curl:latest" .Values.origin.registry }}'
      {{- end }}
      imagePullSecrets: {{ include "router.imagePullSecrets" . }}
      containers:
        - name: router
          image: {{ include "router.image" . }}
          imagePullPolicy: Always
          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: certs
              mountPath: /certs
          ports:
            - containerPort: 8080
              name: frontend
              protocol: TCP
            - containerPort: 9102
              name: prom-metrics
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            {{- if .Values.onprem.enabled }}
            - name: GC_KONG_API_ENDPOINT
              value: {{ include "kong.admin.url" . }}
            - name: GC_GRAFANA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "grafana.fullname" . }}
                  key: "admin-password"
            - name: GC_RBAC_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "postgresql.secretName" . }}
                  key: {{ include "postgresql.adminPasswordKey" . }}
            {{- end }}
            - name: GIN_MODE
              value: "release"
            - name: GC_GROUNDCOVERVERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['groundcover_version']
            - name: ROUTER_VERSION
              value: "{{ .Values.origin.tag }}"
            - name: ROUTER_SENTRY_DSN
              value: "{{ .Values.sentryDsn }}"
          readinessProbe:
            httpGet:
              path: /health
              port: frontend
            initialDelaySeconds: 5
            periodSeconds: 15
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /health
              port: frontend
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5     
{{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
{{- end }}
{{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}     
{{- end }}
      volumes:
        - name: config-volume
          configMap:
            name: router-config
        - name: certs
          secret:
            secretName: {{ include "router.jwt.secretName" . }}
{{ end -}}
