{{ if and .Values.ingress.enabled .Values.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: router-frontend-ingress
  namespace: {{ .Release.Namespace }}
  labels:
    {{- if .Values.additionalLabels }}
  {{ toYaml .Values.additionalLabels | indent 4 }}
  {{- end }}
  annotations:
    kubernetes.io/ingress.class: kong
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: router
                port:
                  number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: router-portal-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: key-auth-plugin
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /client/connect
            pathType: Prefix
            backend:
              service:
                name: router
                port:
                  number: 8080
          - path: /datasources
            pathType: Prefix
            backend:
              service:
                name: router
                port:
                  number: 8080
{{ end }}