apiVersion: v1
kind: Secret
metadata:
  name: {{ include "router.jwt.secretName" . }}
  labels:
    {{- include "router.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "jwt/*").AsSecrets | indent 2 }}
