apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "router.labels" . | nindent 4 }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}
  name: router
  namespace: {{ .Release.Namespace }}