apiVersion: v1
kind: ServiceAccount
metadata:
    {{- if .Values.additionalLabels }}
  labels:
{{ toYaml .Values.additionalLabels | indent 4 }}
    {{- end }}
{{- if .Values.serviceAccount.annotations }}
  annotations:
{{ toYaml .Values.serviceAccount.annotations | indent 4 }}
{{- end }}
  name: router
  namespace: {{ .Release.Namespace }}