{{- if .Values.enabled -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: router
    app.kubernetes.io/name: router
    {{- if .Values.additionalLabels }}
{{ toYaml .Values.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ .Values.origin.tag }}
  name: router
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: frontend
      port: 8080
      protocol: TCP
      targetPort: frontend
  selector:
    app: router
    app.kubernetes.io/name: router
  type: ClusterIP
{{ end -}}