{{- if .Values.onprem.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-plain" (include "router.fullname" .) }}
  annotations:
    konghq.com/protocols: http,https
  labels:
    {{- include "router.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.kong.ingressController.ingressClass }}
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "router.service.name" . }}
                port:
                  name: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-auth" (include "router.fullname" .) }}
  annotations:
    konghq.com/plugins: key-auth
    konghq.com/protocols: http,https
  labels:
    {{- include "router.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.kong.ingressController.ingressClass }}
  rules:
    - http:
        paths:
          - path: /client
            pathType: Prefix
            backend:
              service:
                name: {{ include "router.service.name" . }}
                port:
                  name: frontend
          - path: /datasources
            pathType: Prefix
            backend:
              service:
                name: {{ include "router.service.name" . }}
                port:
                  name: frontend
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-clickhouse" (include "router.fullname" .) }}
  annotations:
    konghq.com/protocols: http,https
    konghq.com/headers.X-Clickhouse-User: default
    konghq.com/plugins: key-auth,clickhouse-ds-rewrite
  labels:
    {{- include "router.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.kong.ingressController.ingressClass }}
  rules:
    - http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ include "router.service.name" . }}
                port:
                  name: frontend
{{- end -}}
