{{ if .Values.global.integrations.agent.enabled }}
apiVersion: v1
data:
  config.yaml: |
    LogLevel: 4
    {{ if .Values.integrationsAgent }}
    {{ if .Values.integrationsAgent.targets }}
    Targets:
    {{ if .Values.integrationsAgent.targets.cloudwatch }}
    {{- range .Values.integrationsAgent.targets.cloudwatch }}
    - Type: "cloudwatch"
      Name: "{{ .name }}"
      StsRegion: "{{ .stsRegion }}"
      RoleArn: "{{ .roleArn }}"
      Regions:
      {{- range .regions }}
        - "{{ . }}"
      {{- end }}
      Namespaces:
      {{- range .namespaces }}
        - "{{ . }}"
      {{- end }}
      {{- if .metrics }}
      Metrics:
        {{- range $namespace, $metrics := .metrics }}
        {{$namespace}}:
        {{- range $metrics }}
          - Name: "{{ . }}"
            Statistics:
        {{- range .statistics }}
            - "{{ . }}"
        {{- end }}
        {{- end }}
        {{- end }}
      {{- end }}
      Exporters:
        - "prometheus"
    {{- end }}
    {{- range .Values.integrationsAgent.targets.additionalExporters }}
        - "{{ . }}"
    {{- end }}
    {{- end }}
    {{ if .Values.integrationsAgent.targets.gcpmetrics }}
    {{- range .Values.integrationsAgent.targets.gcpmetrics }}
    - Type: gcpmetrics
      Name: "{{ .name }}"
      TargetServiceAccount: "{{ .targetServiceAccount }}"
      Regions:
      {{- range .regions }}
        - "{{ . }}"
      {{- end }}
      ProjectIds:
      {{- range .projectIds }}
        - "{{ . }}"
      {{- end }}
      MetricPrefixes:
      {{- range .metricPrefixes }}
        - "{{ . }}"
      {{- end }}
      Exporters:
        - "prometheus"
    {{- end }}
    {{- range .Values.integrationsAgent.targets.additionalExporters }}
        - "{{ . }}"
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}

    Exporters:
    - Type: "prometheus"
      Name: "prometheus"
      url: {{ include "metrics-ingester.cluster.http.base.url" . }}
      TlsSkipVerify: true

    Pprof:
      enabled: {{ include "telemetry.enabled" . }}
      interval: {{ .Values.integrationsAgent.pprof.interval }}
      exponent: {{ .Values.integrationsAgent.pprof.exponent }}
      cpuSamplingDuration: {{ .Values.integrationsAgent.pprof.cpuSamplingDuration }}
      httpUploader:
        enabled: {{ eq .Values.integrationsAgent.pprof.uploaderType "http" }}
        pushURL: {{ printf "%s/upload/pprof" (include "telemetry.metrics.base.url" .) }}
      pyroscopeUploader:
        enabled: {{ eq .Values.integrationsAgent.pprof.uploaderType "pyroscope" }}
        pushURL: {{ include "telemetry.metrics.base.url" . }}
      
    TargetMetricGroups:
      cloudwatch:
        AWS/EC2:
        - Name: CPUCreditBalance
          Statistics:
          - Average
        - Name: CPUCreditUsage
          Statistics:
          - Average
        - Name: CPUSurplusCreditBalance
          Statistics:
          - Average
        - Name: CPUSurplusCreditsCharged
          Statistics:
          - Average
        - Name: CPUUtilization
          Statistics:
          - Average
          - Maximum
        - Name: DiskReadBytes
          Statistics:
          - Average
        - Name: DiskReadOps
          Statistics:
          - Average
        - Name: DiskWriteOps
          Statistics:
          - Average
        - Name: EBSByteBalance%
          Statistics:
          - Average
        - Name: EBSIOBalance%
          Statistics:
          - Average
        - Name: EBSReadBytes
          Statistics:
          - Average
          - Sum
        - Name: EBSReadOps
          Statistics:
          - Average
          - Sum
        - Name: EBSWriteBytes
          Statistics:
          - Average
          - Sum
        - Name: EBSWriteOps
          Statistics:
          - Average
          - Sum
        - Name: NetworkAddressUsage
          Statistics:
          - Average
        - Name: NetworkAddressUsagePeered
          Statistics:
          - Average
        - Name: NetworkIn
          Statistics:
          - Average
          - Maximum
        - Name: NetworkOut
          Statistics:
          - Average
          - Maximum
        - Name: NetworkPacketsIn
          Statistics:
          - Average
        - Name: NetworkPacketsOut
          Statistics:
          - Average
        - Name: StatusCheckFailed
          Statistics:
          - Average
        - Name: StatusCheckFailedInstance
          Statistics:
          - Average
        - Name: StatusCheckFailedSystem
          Statistics:
          - Average
        AWS/ELB:
        - Name: ActiveConnectionCount
          Statistics:
          - Average
        - Name: BackendConnectionErrors
          Statistics:
          - Average
        - Name: ClientTLSNegotiationErrorCount
          Statistics:
          - Average
        - Name: ConsumedLBCapacityUnits
          Statistics:
          - Average
        - Name: ConsumedLCUs
          Statistics:
          - Average
        - Name: EstimatedALBActiveConnectionCount
          Statistics:
          - Average
        - Name: EstimatedALBConsumedLCUs
          Statistics:
          - Average
        - Name: EstimatedALBNewConnectionCount
          Statistics:
          - Average
        - Name: EstimatedProcessedBytes
          Statistics:
          - Average
        - Name: HealthyHostCount
          Statistics:
          - Average
          - Maximum
          - Minimum
        - Name: HealthyHostCountDeduped
          Statistics:
          - Average
        - Name: HTTPCodeBackend2xx
          Statistics:
          - Average
        - Name: HTTPCodeBackend3xx
          Statistics:
          - Average
        - Name: HTTPCodeBackend4xx
          Statistics:
          - Average
        - Name: HTTPCodeBackend5xx
          Statistics:
          - Average
        - Name: HTTPCodeELB4xx
          Statistics:
          - Average
        - Name: HTTPCodeELB500
          Statistics:
          - Average
        - Name: HTTPCodeELB502
          Statistics:
          - Average
        - Name: HTTPCodeELB503
          Statistics:
          - Average
        - Name: HTTPCodeELB504
          Statistics:
          - Average
        - Name: HTTPCodeELB5xx
          Statistics:
          - Average
        - Name: HTTPCodeRedirect
          Statistics:
          - Average
        - Name: HTTPCodeTarget2xx
          Statistics:
          - Average
        - Name: HTTPCodeTarget3xx
          Statistics:
          - Average
        - Name: HTTPCodeTarget4xx
          Statistics:
          - Average
        - Name: HTTPCodeTarget5xx
          Statistics:
          - Average
        - Name: IPv6ProcessedBytes
          Statistics:
          - Average
        - Name: IPv6RequestCount
          Statistics:
          - Average
        - Name: Latency
          Statistics:
          - Average
          - Maximum
          - Minimum
          - p95
          - p99
        - Name: NewConnectionCount
          Statistics:
          - Average
        - Name: ProcessedBytes
          Statistics:
          - Average
        - Name: RequestCount
          Statistics:
          - Average
        - Name: RequestCountPerTarget
          Statistics:
          - Average
        - Name: RuleEvaluations
          Statistics:
          - Average
        - Name: SpilloverCount
          Statistics:
          - Average
          - Maximum
        - Name: SurgeQueueLength
          Statistics:
          - Average
        - Name: TargetConnectionErrorCount
          Statistics:
          - Average
        - Name: TargetResponseTime
          Statistics:
          - Average
          - Maximum
          - p95
          - p99
        - Name: UnhealthyHostCount
          Statistics:
          - Average
          - Maximum
          - Minimum
        - Name: UnhealthyHostCountDeduped
          Statistics:
          - Average
        AWS/S3:
        - Name: 4xxErrors
          Statistics:
            - Average
        - Name: 5xxErrors
          Statistics:
            - Average
        - Name: AllRequests
          Statistics:
            - Average
        - Name: BucketSizeBytes
          Statistics:
            - Average
        - Name: BytesDownloaded
          Statistics:
            - Average
        - Name: BytesPendingReplication
          Statistics:
            - Average
        - Name: BytesUploaded
          Statistics:
            - Average
        - Name: DeleteRequests
          Statistics:
            - Average
        - Name: FirstByteLatency
          Statistics:
            - Average
            - Maximum
            - Minimum
            - p50
            - p90
            - p95
            - p99
        - Name: GetRequests
          Statistics:
            - Average
        - Name: HeadRequests
          Statistics:
            - Average
        - Name: ListRequests
          Statistics:
            - Average
        - Name: NumberOfObjects
          Statistics:
            - Average
        - Name: OperationsFailedReplication
          Statistics:
            - Average
            - SampleCount
            - Sum
        - Name: OperationsPendingReplication
          Statistics:
            - Average
        - Name: PostRequests
          Statistics:
            - Average
        - Name: PutRequests
          Statistics:
            - Average
        - Name: ReplicationLatency
          Statistics:
            - Average
        - Name: TotalRequestLatency
          Statistics:
            - Average
            - Maximum
            - Minimum
            - p50
            - p90
            - p95
            - p99
        AWS/RDS:
        - Name: ActiveTransactions
          Statistics:
            - Average
        - Name: AuroraBinlogReplicaLag
          Statistics:
            - Average
        - Name: AuroraReplicaLag
          Statistics:
            - Average
        - Name: AuroraReplicaLagMaximum
          Statistics:
            - Average
        - Name: AuroraReplicaLagMinimum
          Statistics:
            - Average
        - Name: BackupRetentionPeriodStorageUsed
          Statistics:
            - Average
        - Name: BinLogDiskUsage
          Statistics:
            - Average
        - Name: BlockedTransactions
          Statistics:
            - Average
        - Name: BufferCacheHitRatio
          Statistics:
            - Average
        - Name: BurstBalance
          Statistics:
            - Average
        - Name: CommitLatency
          Statistics:
            - Average
        - Name: CommitThroughput
          Statistics:
            - Average
        - Name: CpuCreditBalance
          Statistics:
            - Average
        - Name: CpuCreditUsage
          Statistics:
            - Average
        - Name: CpuSurplusCreditBalance
          Statistics:
            - Average
        - Name: CpuSurplusCreditsCharged
          Statistics:
            - Average
        - Name: CpuUtilization
          Statistics:
            - Average
        - Name: DatabaseConnections
          Statistics:
            - Average
        - Name: DbLoad
          Statistics:
            - Average
        - Name: DbLoadCpu
          Statistics:
            - Average
        - Name: DbLoadNonCpu
          Statistics:
            - Average
        - Name: DbLoadRelativeToNumVcpus
          Statistics:
            - Average
        - Name: DdlLatency
          Statistics:
            - Average
        - Name: DdlThroughput
          Statistics:
            - Average
        - Name: Deadlocks
          Statistics:
            - Average
        - Name: DeleteLatency
          Statistics:
            - Average
        - Name: DeleteThroughput
          Statistics:
            - Average
        - Name: DiskQueueDepth
          Statistics:
            - Average
        - Name: DmlLatency
          Statistics:
            - Average
        - Name: DmlThroughput
          Statistics:
            - Average
        - Name: EngineUptime
          Statistics:
            - Average
        - Name: FailedSqlserverAgentJobsCount
          Statistics:
            - Average
        - Name: FreeLocalStorage
          Statistics:
            - Average
        - Name: FreeStorageSpace
          Statistics:
            - Average
        - Name: FreeableMemory
          Statistics:
            - Average
        - Name: InsertLatency
          Statistics:
            - Average
        - Name: InsertThroughput
          Statistics:
            - Average
        - Name: LoginFailures
          Statistics:
            - Average
        - Name: MaximumUsedTransactionIds
          Statistics:
            - Average
        - Name: NetworkReceiveThroughput
          Statistics:
            - Average
        - Name: NetworkThroughput
          Statistics:
            - Average
        - Name: NetworkTransmitThroughput
          Statistics:
            - Average
        - Name: OldestReplicationSlotLag
          Statistics:
            - Average
        - Name: Queries
          Statistics:
            - Average
        - Name: RdstoAuroraPostgreSqlReplicaLag
          Statistics:
            - Average
        - Name: ReadIops
          Statistics:
            - Average
        - Name: ReadLatency
          Statistics:
            - Average
        - Name: ReadThroughput
          Statistics:
            - Average
        - Name: ReplicaLag
          Statistics:
            - Average
        - Name: ReplicationSlotDiskUsage
          Statistics:
            - Average
        - Name: ResultSetCacheHitRatio
          Statistics:
            - Average
        - Name: SelectLatency
          Statistics:
            - Average
        - Name: SelectThroughput
          Statistics:
            - Average
        - Name: SnapshotStorageUsed
          Statistics:
            - Average
        - Name: TransactionLogsDiskUsage
          Statistics:
            - Average
        - Name: TransactionLogsGeneration
          Statistics:
            - Average
        - Name: UpdateLatency
          Statistics:
            - Average
        - Name: UpdateThroughput
          Statistics:
            - Average
        - Name: VolumeReadIOPS
          Statistics:
            - Average
        - Name: VolumeWriteIOPS
          Statistics:
            - Average
        - Name: VolumeReadThroughput
          Statistics:
            - Average
        - Name: VolumeWriteThroughput
          Statistics:
            - Average
        - Name: VolumeBytesUsed
          Statistics:
            - Average
        - Name: WriteIops
          Statistics:
            - Average
        - Name: WriteLatency
          Statistics:
            - Average
        - Name: WriteThroughput
          Statistics:
            - Average
        AWS/SQS:
        - Name: ApproximateAgeOfOldestMessage
          Statistics: 
          - Average
        - Name: ApproximateNumberOfMessagesDelayed
          Statistics: 
          - Average
        - Name: ApproximateNumberOfMessagesNotVisible
          Statistics: 
          - Average
        - Name: ApproximateNumberOfMessagesVisible
          Statistics: 
          - Average
        - Name: NumberOfEmptyReceives
          Statistics: 
          - Average
        - Name: NumberOfMessagesDeleted
          Statistics: 
          - Average
        - Name: NumberOfMessagesReceived
          Statistics: 
          - Average
        - Name: NumberOfMessagesSent
          Statistics: 
          - Average
        - Name: SentMessageSize
          Statistics: 
          - Average
      
kind: ConfigMap
metadata:
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    {{- if .Values.integrationsAgent.additionalLabels }}
{{ toYaml .Values.integrationsAgent.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.integrationsAgent.additionalAnnotations }}
{{ toYaml .Values.integrationsAgent.additionalAnnotations | indent 4 }}
    {{- end }}
  name: integrations-agent-config
  namespace: {{ .Release.Namespace }}
{{ end }}
