{{- if .Values.ingress.tls.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
    name: {{ include "incloud-ingress.certificate.name" . }}
spec:
    secretName: {{ include "incloud-ingress.certificate.name" . }}
    issuerRef:
        name: letsencrypt
        kind: ClusterIssuer
    dnsNames: {{ include "incloud-ingress.certificate.dnsNames" .  | nindent 8 }}
    renewBefore: {{ .Values.ingress.tls.certificate.renewBefore }}
{{- end }}