{{- if .Values.global.ingress.enableTLS }}
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
    name: letsencrypt
spec:
    acme:
        server: {{ .Values.global.ingress.certs.certificate.acme.server }}
        privateKeySecretRef:
            name: private-key-issuer
        solvers:
            - http01:
                ingress:
                    class: kong
{{- end }}