apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-grpc" (include "opentelemetry-collector.fullname" .) }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
    {{- include "opentelemetry-collector.component" . | nindent 4 }}
  annotations:
    konghq.com/protocol: grpc
spec:
  type: ClusterIP
  ports:
    - name: otlp
      protocol: {{ index .Values.global "opentelemetry-collector" "ports" "otlp" "protocol" }}
      port: {{ index .Values.global "opentelemetry-collector" "ports" "otlp" "servicePort" | int }}
      targetPort: {{ index .Values.global "opentelemetry-collector" "ports" "otlp" "containerPort" | int }}
  selector:
    {{- include "opentelemetry-collector.selectorLabels" . | nindent 4 }}
    {{- include "opentelemetry-collector.component" . | nindent 4 }}
