apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-grpc" (include "incloud-ingress.name" .) }}
  annotations:
    konghq.com/headers.content-type: application/grpc
    konghq.com/plugins: {{ printf "%s-auth" .Release.Name | quote }}
    konghq.com/protocols: {{ ternary "grpcs" "grpc" .Values.kong.proxy.tls.enabled | quote }}
spec:
  ingressClassName: kong
  rules:
    - host: {{ splitList ":" (include "opentelemetry-collector.otlp.grpc.url" .) | first }} 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-grpc" (include "opentelemetry-collector.fullname" .) }}
                port:
                  number: {{ index .Values.global "opentelemetry-collector" "ports" "otlp" "servicePort" | int }}
