apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "incloud-ingress.name" . }}-version-http-ingress
  annotations:
    konghq.com/protocols: "https"
    konghq.com/https-redirect-status-code: "301"
    konghq.com/plugins: incloud-auth
spec:
  ingressClassName: kong
  rules:
    - host: {{ required "A valid api.host is required!" .Values.api.host | quote }} 
      http:
        paths:
          - path: /version
            pathType: Exact
            backend:
              service:
                name: {{ include "shepherd.name" . }}
                port:
                  number: 8080