{{- if .Values.internalIngress.enabled }}
apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: {{ .Values.internalIngress.ingressClassName }}
  labels:
    {{- include "incloud-ingress.labels" . | nindent 4 }}
    app.kubernetes.io/name: kong-internal
spec:
  controller: ingress-controllers.konghq.com/kong-internal
{{- end }}
