apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: {{ .Values.auth.namePrefix }}-auth
plugin: key-auth

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.auth.namePrefix }}-api-key
type: Opaque
stringData:
  kongCredType: "key-auth"
  key: {{ .Values.global.groundcover_token }}

---

apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: {{ .Values.auth.namePrefix }}-api
  annotations:
    kubernetes.io/ingress.class: {{ .Values.kong.ingressController.ingressClass }}
    checksum/config: {{ .Values.global.groundcover_token | sha256sum }}
username: incloud-api
credentials:
- {{ .Values.auth.namePrefix }}-api-key