---

apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: {{ printf "%s-auth" .Release.Name }}
config:
  key_names:
    - apikey
    - dd-api-key
    - X-Amz-Firehose-Access-Key
    - Authorization
{{- if .Values.datasource.enabled }}
    - X-ClickHouse-Key
{{- end }}
plugin: key-auth

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-api-key" .Release.Name }}
  labels:
    konghq.com/credential: key-auth
type: Opaque
stringData:
  key: {{ .Values.global.groundcover_token }}

---

apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: {{ printf "%s-api" .Release.Name }}
  annotations:
    checksum/config: {{ .Values.global.groundcover_token | sha256sum }}
    kubernetes.io/ingress.class: {{ .Values.kong.ingressController.ingressClass }}
username: api
credentials:
  - {{ printf "%s-api-key" .Release.Name }}

---

{{- if .Values.datasource.enabled -}}
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: clickhouse-ds-rewrite
config:
  replace:
    headers:
      - {{ printf "X-ClickHouse-User: %s" (include "clickhouse.username" .) | quote }}
      - {{ printf "X-ClickHouse-Key: %s" (include "clickhouse.password" .) | quote }}
plugin: request-transformer
{{- end -}}