{{- if (.Values.global.clickhouse.ha | default dict).enabled }}
{{ include "clickhouseKeeper.service" (dict "root" . "values" .Values.standbyKeeper "valuesPath" "standbyKeeper" "nameSuffix" "clickhouse-standby-keeper") }}
{{- end }}
