{{ if and .Values.backend.enabled (typeIs "bool" .Values.global.clickhouse.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "clickhouse.secretName" . }}
  annotations:
    helm.sh/resource-policy: "keep"
type: Opaque
stringData:
  {{ template "clickhouse.secretKey" . }}: {{ include "clickhouse.password" . | quote }}
{{ end }}
