{{ if .Values.backend.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{ with .Values.global.groundcoverLabels }} 
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.grafana.additionalLabels }}
{{ toYaml .Values.grafana.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.origin.tag }}
    {{- if .Values.grafana.additionalAnnotations }}
{{ toYaml .Values.grafana.additionalAnnotations | indent 4 }}
    {{- end }}
  name: grafana
  namespace: {{ .Release.Namespace }}
{{ end -}}
