apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: secret-manager-rolebinding
  namespace: {{ .Values.namespace | default .Release.Namespace | default "default" }}
subjects:
  - kind: ServiceAccount
    name: {{ include "keep.serviceAccountName" . }}
    namespace: {{ .Values.namespace | default .Release.Namespace | default "default" }}
roleRef:
  kind: Role
  name: secret-manager-role
  apiGroup: rbac.authorization.k8s.io
