annotations:
  artifacthub.io/category: monitoring-logging
  artifacthub.io/changes: |
    - '**Update note**: This release contains new CRDs VLCluster and VLSingle. It requires to perform CRD versions update.'
    - Support scrape and probe CRs validation webhooks
    - updates operator to [v0.59.1](https://github.com/VictoriaMetrics/operator/releases/tag/v0.59.1) version
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Sources
      url: https://github.com/VictoriaMetrics/helm-charts/tree/master/charts/victoria-metrics-operator
    - name: Charts repo
      url: https://victoriametrics.github.io/helm-charts/
    - name: Docs
      url: https://docs.victoriametrics.com/operator
    - name: Changelog
      url: https://docs.victoriametrics.com/operator/changelog
  artifacthub.io/operator: "true"
apiVersion: v2
appVersion: v0.59.1
dependencies:
- name: victoria-metrics-common
  repository: https://victoriametrics.github.io/helm-charts
  version: 0.0.*
- condition: crds.plain
  name: crds
  repository: ""
  version: 0.0.*
description: VictoriaMetrics Operator
home: https://github.com/VictoriaMetrics/operator
icon: https://avatars.githubusercontent.com/u/43720803?s=200&v=4
keywords:
- victoriametrics
- operator
- monitoring
- kubernetes
- observability
- tsdb
- metrics
- metricsql
- timeseries
kubeVersion: '>=1.25.0-0'
name: victoria-metrics-operator
sources:
- https://github.com/VictoriaMetrics/helm-charts
- https://github.com/VictoriaMetrics/operator
type: application
version: 0.49.1
