{{ if .Values.global.agent.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "groundcover.fullname" . }}-groundcover-metadata-fetcher
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.rbac.annotations }}
{{ toYaml .Values.rbac.annotations | indent 4 }}
    {{- end }}
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    {{- if .Values.rbac.labels }}
{{ toYaml .Values.rbac.labels | indent 4 }}
    {{- end }}
rules:
- apiGroups:
  - "apps"
  - ""
  - batch
  resources:
  - jobs
  - cronjobs
  - pods
  - services
  - endpoints
  - namespaces
  - daemonsets
  - replicasets
  - nodes
  - deployments
  - nodes
  - statefulsets
  - events
  - nodes/metrics
  - nodes/proxy
  - nodes/stats
  - replicationcontrollers
  - persistentvolumeclaims
  - persistentvolumes
  {{- if .Values.k8sWatcher.watch.configmap.enabled }}
  - configmaps
  {{- end }}
  {{- if .Values.k8sWatcher.watch.secret.enabled }}
  - secrets
  {{- end }}
  verbs:
  - list
  - watch
  - get
{{- if .Values.k8sWatcher.watch.verticalPodAutoscaler.enabled }}
- apiGroups:
  - "autoscaling.k8s.io"
  resources:  
  - verticalpodautoscalers
  verbs:
  - list
  - get
  - watch
{{- end }}
{{- if .Values.k8sWatcher.watch.crd.enabled }}
- apiGroups:
  - "*"
  resources:
  - customresourcedefinitions
  verbs:
  - list
  - watch
  - get
{{- range $key, $value := .Values.k8sWatcher.watch.crd.allowedKinds }}
- apiGroups:
  - "{{ $value.group }}"
  resources:
  - {{ $value.kindPlural }}
  verbs:
  - list
  - watch
  - get
{{- end }}
{{- end }}
{{- if and .Values.rbac.pspEnabled (.Capabilities.APIVersions.Has "policy/v1beta1") }}
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [{{ template "groundcover.fullname" . }}]
{{- end }}
{{- end }}