apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "groundcover.fullname" . }}-groundcover-metadata-fetcher
  annotations:
    groundcover_version: {{ .Values.origin.tag }}
    {{- if .Values.rbac.annotations }}
{{ toYaml .Values.rbac.annotations | indent 4 }}
    {{- end }}
  labels:
    {{- if .Values.rbac.labels }}
{{ toYaml .Values.rbac.labels | indent 4 }}
    {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "groundcover.fullname" . }}-groundcover-metadata-fetcher
subjects:
- kind: ServiceAccount
  name: k8s-watcher
  namespace: {{ .Release.Namespace }}
- kind: ServiceAccount
  name: alligator
  namespace: {{ .Release.Namespace }}
