{{ if .Values.agent.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "groundcover.fullname" . }}-groundcover-metadata-fetcher
  annotations:
    groundcover_version: {{ .Values.origin.tag }}
    {{- if .Values.rbac.annotations }}
{{ toYaml .Values.rbac.annotations | indent 4 }}
    {{- end }}
  labels:
    {{ with .Values.global.groundcoverLabels }} 
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.rbac.labels }}
{{ toYaml .Values.rbac.labels | indent 4 }}
    {{- end }}
rules:
- apiGroups:
  - "apps"
  - ""
  resources:
  - pods
  - services
  - endpoints
  - namespaces
  - daemonsets
  - replicasets
  - nodes
  - deployments
  - nodes
  - statefulsets
  - events
  - nodes/metrics
  - nodes/stats
  verbs:
  - list
  - watch
  - get
{{- if .Values.rbac.pspEnabled }}
- apiGroups:      ['extensions']
  resources:      ['podsecuritypolicies']
  verbs:          ['use']
  resourceNames:  [{{ template "groundcover.fullname" . }}]
{{- end }}
{{- end }}