apiVersion: v1
kind: Secret
metadata:
  labels:
    {{ with .Values.global.groundcoverLabels }} 
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.config.labels }}
{{ toYaml .Values.config.labels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.config.annotations }}
{{ toYaml .Values.config.annotations | indent 4 }}
    {{- end }}
  name: groundcover-config
  namespace: {{ .Release.Namespace }}
stringData:
  GC_CLUSTER_ID: {{ template "groundcover.clusterId" . }}
  GC_REGION: {{ template "groundcover.region" . }}
  GC_VERSION: {{ default .Chart.AppVersion .Values.global.origin.tag }}

type: Opaque