apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    {{- if .Values.config.labels }}
{{ toYaml .Values.config.labels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.config.annotations }}
{{ toYaml .Values.config.annotations | indent 4 }}
    {{- end }}
  name: groundcover-config
  namespace: {{ .Release.Namespace }}
stringData:
  GC_CLUSTER_ID: {{ include "groundcover.clusterId" . }}
  GC_REGION: {{ include "groundcover.region" . }}
  GC_VERSION: {{ default .Chart.AppVersion .Values.global.origin.tag }}
  GC_ENV: {{ include "groundcover.env" . | quote }}
type: Opaque
