{{ if and .Values.global.backend.enabled (index .Values "statefulset-modifier" "enabled") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "statefulset-modifier.fullname" . }}
  labels:
  {{- include "groundcover.labels" . | nindent 4 }}
  annotations:
  {{- include "statefulset-modifier.rbac.annotations" $ | nindent 4 }}
{{- end -}}
