enabled: true
additionalLabels:
mode: cloud
origin:
  registry: public.ecr.aws/groundcovercom
  tag: 1.4.7
serviceAccount:
  annotations:
repository: router
configuration:
  Activity:
    CheckInterval: 5m
    StaleAfter: 30m
  LogLevel: 4
  Reverse: true
  groundcoverVersion: ""
  Portal:
    Host: "portal"
    Port: "5555"
  ListenPort: "8080"
  Auth0:
    RequiredScope: "access:router"
    OrgClaimKey: "https://client.info/org"
    Audience: "https://groundcover"
    Tenant: "auth.groundcover.com"
  RBAC:
    Migrations:
      Path: migrations
  Reporter:
    ttl: 10m
    PurgeInterval: 10m
    Bucket: "metrics.groundcover.com"
    ReportInterval: 10m
    StoreStatus: true
ingress:
  enabled: false
  host: domain.groundcover.com
  externalName:
  frontend:
    annotations: {}
  portal:
    annotations: {}
apiIngress:
  enabled: false
  host: domain.groundcover.com
resources:
  requests:
    cpu: 1000m
    memory: 1024Mi
  limits:
    memory: 2048Mi
    cpu: 1500m
nodeSelector: {}
tolerations: []
