enabled: true

additionalLabels:

mode: cloud

origin:
  registry: public.ecr.aws/k8g4n2c4
  tag: version

repository: router

versionDb:
  host:
  port:
  name:
  user:
  password:

versionBucket:
  name:
  path:
  region:

ingress:
  enabled: false
  host: domain.groundcover.com
  externalName:

resources:
  requests:
    cpu: 1000m
    memory: 1024Mi
  limits:
    memory: 2048Mi
    cpu: 1500m