{
 "title": "Cluster Overview Dashboard",
 "description": "Cluster Overview by groundcover",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "ds_prom", "label": "cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(groundcover_resource_total_counter{type=\"container_info\"}, namespace)"
    }
   },
   { "name": "ds_sql", "label": "SQL Data Source", "query": "postgres" },
   { "name": "ds_logs", "label": "Logs Data Source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Issue Velocity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "alias(sum(rate(groundcover_resource_error_counter{type=\"http\", namespace='$namespace'}[$__rate_interval])), 'HTTP')"
    },
    {
     "expr": "alias(sum(rate(groundcover_resource_error_counter{type=\"dns\", namespace='$namespace'}[$__rate_interval])), 'DNS')"
    },
    {
     "expr": "alias(sum(rate(groundcover_resource_error_counter{type=~\"postgresql|mysql\", namespace='$namespace'}[$__rate_interval])), 'SQL')"
    },
    {
     "expr": "alias(sum(rate(groundcover_resource_error_counter{type=\"grpc\", namespace='$namespace'}[$__rate_interval])), 'GRPC')"
    }
   ]
  },
  {
   "title": "Number of Nodes",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(groundcover_resource_total_counter{type=\"container_info\", namespace='$namespace'}) by (node_name))"
    }
   ]
  },
  {
   "title": "Number of Workloads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(groundcover_resource_total_counter{type=\"container_info\", namespace='$namespace'}) by (workload_name))"
    }
   ]
  },
  {
   "title": "Number of Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(groundcover_resource_total_counter{type=\"container_info\", namespace='$namespace'}) by (pod_name))"
    }
   ]
  },
  {
   "title": "Total CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "mCPU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(groundcover_cpu_usage_m_cpu{namespace='$namespace'})"
    }
   ]
  },
  {
   "title": "Total Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(groundcover_resident_set_size_bytes{namespace='$namespace'})"
    }
   ]
  },
  {
   "title": "Infrastructure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilisation by Workload",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 19, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "mCPU" } },
     "targets": [
      {
       "expr": "topk(50, avg by (workload_name) (groundcover_cpu_usage_m_cpu{namespace='$namespace'}))",
       "legendFormat": "{{workload_name}}"
      }
     ]
    },
    {
     "title": "Most CPU Intensive Workloads",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "mCPU" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, (avg (groundcover_cpu_usage_m_cpu{namespace='$namespace'}) by (workload_name)))",
       "legendFormat": "{{workload_name}}"
      }
     ]
    },
    {
     "title": "Memory Utilisation by Workload",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 19, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "topk(50, avg by (workload_name) (groundcover_resident_set_size_bytes{namespace='$namespace'}))",
       "legendFormat": "{{workload_name}}"
      }
     ]
    },
    {
     "title": "Most Memory Intensive Workloads",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, (sum (groundcover_resident_set_size_bytes{namespace='$namespace'}) by (workload_name)))",
       "legendFormat": "{{workload_name}}"
      }
     ]
    },
    {
     "title": "Memory Out of Limit by Workload",
     "type": "stat",
     "gridPos": { "h": 10, "w": 19, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(7, clamp_max(avg by (workload_name) (groundcover_memory_utilization{namespace='$namespace'}), 1))",
       "legendFormat": "{{workload_name}}"
      }
     ]
    },
    {
     "title": "Most OOM Frequent Workloads",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 34 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, sum (delta(groundcover_resource_error_counter{type=\"container_state\", namespace='$namespace', state_reason=\"OOMKilled\"}[$__range])) by (workload_name))",
       "legendFormat": "{{workload_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests & Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "alias(sum(rate (groundcover_resource_total_counter{type=~\"http|grpc\", namespace='$namespace'}[$__rate_interval])), 'OK')"
      },
      {
       "expr": "alias(sum(rate (groundcover_resource_error_counter{type=~\"http|grpc\",namespace='$namespace'}[$__rate_interval])), 'Error')"
      }
     ]
    },
    {
     "title": "Top Error Rate by Workload",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, sum(rate (groundcover_resource_error_counter{type=~\"http|grpc\",namespace='$namespace'}[$__rate_interval])) by (workload_name))",
       "legendFormat": "{{workload_name}}"
      }
     ]
    },
    {
     "title": "Workload Latency",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 19, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(50, avg by (workload_name) (groundcover_resource_latency_seconds{type=~\"grpc|http\",namespace='$namespace', role=\"server\", quantile=\"0.50\"}))",
       "legendFormat": "{{workload_name}}"
      }
     ]
    },
    {
     "title": "Slowest Workloads",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, (avg by (workload_name) (groundcover_resource_latency_seconds{type=~\"http|grpc\",namespace='$namespace', role=\"server\", quantile=\"0.50\"})))",
       "legendFormat": "{{workload_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests & Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "alias(sum(rate (groundcover_resource_total_counter{type=~\"mysql|postgresql\",namespace='$namespace'}[$__rate_interval])), 'OK')"
      },
      {
       "expr": "alias(sum(rate (groundcover_resource_error_counter{type=~\"mysql|postgresql\", namespace='$namespace'}[$__rate_interval])), 'Error')"
      }
     ]
    },
    {
     "title": "Top Error Rate by Workload",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, sum(rate (groundcover_resource_error_counter{type=~\"mysql|postgresql\", namespace='$namespace'}[$__rate_interval])) by (workload_name))",
       "legendFormat": "{{workload_name}}"
      }
     ]
    },
    {
     "title": "Latency by SQL Server",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(20, avg(groundcover_resource_latency_seconds{type=~\"mysql|postgresql\", namespace='$namespace', role=\"client\", quantile=\"0.50\"}) by (remote_service_name))",
       "legendFormat": "{{remote_service_name}}"
      }
     ]
    },
    {
     "title": "Top Query Rate by Workload",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(20, sum(rate(groundcover_resource_total_counter{type=~\"mysql|postgresql\", namespace='$namespace', role=\"client\"}[$__rate_interval])) by (workload_name))",
       "legendFormat": "{{workload_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests & Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "alias(sum(rate (groundcover_resource_total_counter{type=\"dns\", namespace='$namespace'}[$__rate_interval])), 'OK')"
      },
      {
       "expr": "alias(sum(rate (groundcover_resource_error_counter{type=\"dns\", namespace='$namespace'}[$__rate_interval])), 'Error')"
      }
     ]
    },
    {
     "title": "Top Error Rate by Workload",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, sum(rate (groundcover_resource_error_counter{type=\"dns\", namespace='$namespace'}[$__rate_interval])) by (workload_name))",
       "legendFormat": "{{workload_name}}"
      }
     ]
    },
    {
     "title": "Latency by DNS Server",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(20, avg by (remote_addr) (groundcover_resource_latency_seconds{type=\"dns\", namespace='$namespace', role=\"client\", quantile=\"0.50\"}))",
       "legendFormat": "{{remote_addr}}"
      }
     ]
    },
    {
     "title": "Return Codes",
     "type": "piechart",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 26 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (response_return_code) (groundcover_resource_total_counter{type=\"dns\", namespace='$namespace', role=\"client\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Requests & Error Rate",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 19, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "alias(sum(rate (groundcover_resource_total_counter{type=\"kafka\", namespace='$namespace'}[$__rate_interval])), 'OK')"
      },
      {
       "expr": "alias(sum(rate (groundcover_resource_error_counter{type=\"kafka\", namespace='$namespace'}[$__rate_interval])), 'Error')"
      }
     ]
    },
    {
     "title": "Top Error Rate by Workload",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 5, "x": 19, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, sum(rate (groundcover_resource_error_counter{type=\"kafka\",namespace='$namespace'}[$__rate_interval])) by (workload_name))",
       "legendFormat": "{{workload_name}}"
      }
     ]
    },
    {
     "title": "Lag by Topic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 15, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "msgs" } },
     "targets": [
      {
       "expr": "topk(20, max(groundcover_calc_lagged_messages{type=\"kafka\", namespace='$namespace', client_type=\"Fetcher\"}) by (topic))",
       "legendFormat": "{{topic}}"
      }
     ]
    },
    {
     "title": "Most Active Topics",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 9, "x": 15, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "msgs/s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, sum(rate(groundcover_resource_total_counter{type=\"kafka\", namespace='$namespace', client_type=\"Fetcher\"}[$__rate_interval])) by (topic))"
      }
     ]
    },
    {
     "title": "Lag by Consumer Workload",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "msgs" } },
     "targets": [
      {
       "expr": "topk(20, max(groundcover_calc_lagged_messages{type=\"kafka\", namespace='$namespace', client_type=\"Fetcher\"}) by (workload_name))",
       "legendFormat": "{{workload_name}}"
      }
     ]
    }
   ]
  }
 ]
}