{
 "title": "Cluster Issues Dashboard",
 "description": "Cluster Issues by groundcover",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prom", "label": "cluster", "query": "prometheus" },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(groundcover_resource_total_counter{type=\"container_info\"}, namespace)"
    }
   },
   { "name": "ds_sql", "label": "SQL Data Source", "query": "postgres" },
   { "name": "ds_logs", "label": "Logs Data Source", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Workload Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(16, count by(workload_name) (\n    (\n    groundcover_resource_error_counter{type=~\"http|grpc\", namespace='$namespace', role='server'}\n    or groundcover_resource_error_counter{type=~\"postgresql|mysql\", namespace='$namespace', role='client'}\n    or groundcover_resource_error_counter{type=\"dns\", namespace='$namespace', role='client'}\n    )[$__range]\n   )\n   or \n   (group by(workload_name) (groundcover_resource_total_counter{type=\"container_info\", namespace='$namespace'}[$__range]) - 1)\n )",
     "legendFormat": "{{workload_name}}"
    }
   ]
  },
  {
   "title": "Number of Issues",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(\n    (groundcover_resource_error_counter{type=~\"http|grpc\",namespace='$namespace', role='server'}\n    or groundcover_resource_error_counter{type=~\"postgresql|mysql\", namespace='$namespace', role='client'}\n    or groundcover_resource_error_counter{type=\"dns\", namespace='$namespace', role='client'})[$__range]\n)"
    }
   ]
  },
  {
   "title": "Number of Workloads",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(groundcover_resource_total_counter{type=\"container_info\",namespace='$namespace'}[$__range]) by (workload_name))"
    }
   ]
  },
  {
   "title": "Number of Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(groundcover_resource_total_counter{type=\"container_info\",namespace='$namespace'}[$__range]) by (pod_name))"
    }
   ]
  },
  {
   "title": "Open Issues",
   "type": "table",
   "gridPos": { "h": 14, "w": 9, "x": 15, "y": 7 },
   "targets": [
    {
     "rawSql": "(select \ni.hash_id  as issueId,\nlast(r.product_type, se.start_time) as issueType,\nlast(i.attributes->>'http.status_code'::text, se.start_time) as issueCode,\nlast(se.role, se.start_time) as role,\nlast(r.attributes->>'http.route', se.start_time) as resourceName,\nlast(se.namespace, se.start_time) as namespace,\nlast(se.name, se.start_time) as workloadName,\nlast(sere.remote_service_name, se.start_time) as remoteServiceName,\nlast(sere.remote_namespace, se.start_time) as remoteNamespace,\nlast(i.reason, se.start_time) as reason,\nlast(r.attributes->>'http.method', se.start_time) as subType,\nto_char(min(se.start_time), 'YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"') as firstSeen,\nto_char(max(se.start_time), 'YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"') as lastSeen,\ncount(*) as incidents\nfrom _ps_trace.issue i \njoin _ps_trace.resource r on r.hash_id=i.resource_hash \njoin _ps_trace.span_entities se on i.hash_id=se.issue_hash\njoin _ps_trace.span_entity_with_remote_entity sere on sere.span_id=se.span_id\nwhere (r.product_type = 'http' or r.product_type = 'grpc') and $__timeFilter(se.start_time) and se.namespace = '$namespace'\ngroup by issueId, se.perspective_entity_hash\norder by lastSeen desc \nlimit 20)\n\nunion\n\n(select \ni.hash_id  as issueId,\nlast(r.product_type, se.start_time) as issueType,\nlast(r.attributes->>'state'::text, se.start_time) as issueCode,\n'' as role, \nlast(r.attributes->>'container_name', se.start_time) as resourceName,\nlast(se.namespace, se.start_time) as namespace,\nlast(se.name, se.start_time) as workloadName,\n'' as remoteServiceName , \n'' as remoteNamespace, \nlast(i.attributes->>'exit_code'::text, se.start_time) as reason,\n'Container Error' as subType,\nto_char(min(se.start_time), 'YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"') as firstSeen,\nto_char(max(se.start_time), 'YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"') as lastSeen,\ncount(*) as incidents\nfrom _ps_trace.issue i \njoin _ps_trace.resource r on r.hash_id=i.resource_hash \njoin _ps_trace.span_entities se on i.hash_id=se.issue_hash\njoin _ps_trace.span_entity_with_remote_entity sere on sere.span_id=se.span_id\nwhere r.product_type = 'container_state' and $__timeFilter(se.start_time) and se.namespace = '$namespace'\ngroup by issueId, se.perspective_entity_hash\norder by lastSeen desc \nlimit 20)\n\nunion\n\n(select \ni.hash_id  as issueId,\nlast(r.product_type, se.start_time) as issueType,\nlast(i.attributes->>'response_status'::text, se.start_time) as issueCode,\nlast(se.role, se.start_time) as role, \nlast(r.attributes->>'query_fingerprint', se.start_time) as resourceName,\nlast(se.namespace, se.start_time) as namespace,\nlast(se.name, se.start_time) as workloadName,\nlast(sere.remote_service_name, se.start_time) as remoteServiceName,\nlast(sere.remote_namespace, se.start_time) as remoteNamespace,\nlast(i.reason, se.start_time) as reason,\nlast(r.attributes->>'db.system', se.start_time) as subType,\nto_char(min(se.start_time), 'YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"') as firstSeen,\nto_char(max(se.start_time), 'YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"') as lastSeen,\ncount(*) as incidents\nfrom _ps_trace.issue i \njoin _ps_trace.resource r on r.hash_id=i.resource_hash \njoin _ps_trace.span_entities se on i.hash_id=se.issue_hash\njoin _ps_trace.span_entity_with_remote_entity sere on sere.span_id=se.span_id\nwhere (r.product_type = 'postgresql' or r.product_type = 'mysql') and $__timeFilter(se.start_time) and se.namespace = '$namespace'\ngroup by issueId, se.perspective_entity_hash\norder by lastSeen desc \nlimit 20)\n\nunion\n\n(select \ni.hash_id  as issueId,\nlast(r.product_type, se.start_time) as issueType,\nlast(i.attributes->>'error_code'::text, se.start_time) as issueCode,\nlast(se.role, se.start_time) as role, \nCONCAT(last(r.attributes->>'messaging.destination', se.start_time), ',', last(r.attributes->>'partition'::text, se.start_time)) as resourceName,\nlast(se.namespace, se.start_time) as namespace,\nlast(se.name, se.start_time) as workloadName,\nlast(sere.remote_service_name, se.start_time) as remoteServiceName,\nlast(sere.remote_namespace, se.start_time) as remoteNamespace,\nlast(i.reason, se.start_time) as reason,\nlast(r.attributes->>'client_type', se.start_time) as subType,\nto_char(min(se.start_time), 'YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"') as firstSeen,\nto_char(max(se.start_time), 'YYYY-MM-DD\"T\"HH24:MI:SS.US\"Z\"') as lastSeen,\ncount(*) as incidents\nfrom _ps_trace.issue i \njoin _ps_trace.resource r on r.hash_id=i.resource_hash \njoin _ps_trace.span_entities se on i.hash_id=se.issue_hash\njoin _ps_trace.span_entity_with_remote_entity sere on sere.span_id=se.span_id\nwhere r.product_type = 'kafka' and $__timeFilter(se.start_time) and se.namespace = '$namespace'\ngroup by issueId, se.perspective_entity_hash\norder by lastSeen desc \nlimit 20)\n\n"
    }
   ]
  },
  {
   "title": "Issue Velocity",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 15, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "alias(sum(rate(groundcover_resource_error_counter{type=~\"http|grpc\", namespace='$namespace'}[$__rate_interval])), 'HTTP/GRPC')"
    },
    {
     "expr": "alias(sum(rate(groundcover_resource_error_counter{type=\"dns\", namespace='$namespace'}[$__rate_interval])), 'DNS')"
    },
    {
     "expr": "alias(sum(rate(groundcover_resource_error_counter{type=~\"postgresql|sql\", namespace='$namespace'}[$__rate_interval])), 'SQL')"
    }
   ]
  }
 ]
}