{
 "title": "K8S",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "node",
    "query": {
     "query": "label_values(groundcover_resource_total_counter{type=\"container_info\"}, node_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(groundcover_resource_total_counter{type=\"container_info\"}, namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node_name) (rate(groundcover_node_m_cpu_usage_seconds_total{})) / sum by (node_name) (groundcover_node_allocatable_cpum_cpu{})",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Mem Utilization",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (node_name) (groundcover_node_mem_working_set_bytes{}) / sum by (node_name) (groundcover_node_allocatable_mem_bytes{})",
     "legendFormat": "{{ node_name }}"
    }
   ]
  },
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Node Usage (CPU)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "mCPU" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (node_name) (rate(groundcover_node_m_cpu_usage_seconds_total{})))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Node Usage (Mem)",
     "type": "stat",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sort_desc(sum by (node_name) (groundcover_node_mem_working_set_bytes{}))",
       "legendFormat": "{{node_name}}"
      }
     ]
    },
    {
     "title": "Node Pressure (Mem)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(groundcover_node_mem_working_set_bytes{node_name=~'$node'})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(groundcover_container_memory_limit_bytes{node_name=~'$node'})",
       "legendFormat": "Max"
      },
      {
       "expr": "sum(groundcover_container_memory_request_bytes{node_name=~'$node'})",
       "legendFormat": "Min"
      },
      {
       "expr": "sum(groundcover_node_allocatable_mem_bytes{node_name=~'$node'})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Node Pressure (CPU)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 11, "x": 10, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "mCPU" } },
     "targets": [
      {
       "expr": "rate(groundcover_node_m_cpu_usage_seconds_total{node_name=~'$node'})",
       "legendFormat": "Used"
      },
      {
       "expr": "sum(groundcover_container_cpu_limit_m_cpu{node_name=~'$node'})",
       "legendFormat": "Max"
      },
      {
       "expr": "sum(groundcover_container_cpu_request_m_cpu{node_name=~'$node'})",
       "legendFormat": "Min"
      },
      {
       "expr": "sum(groundcover_node_allocatable_cpum_cpu{node_name=~'$node'})",
       "legendFormat": "Limit"
      }
     ]
    },
    {
     "title": "Under-utilizing workloads (CPU)",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bottomk(10, (avg by (workload_name, namespace) (rate(groundcover_container_m_cpu_usage_seconds_total{node_name=~'$node', namespace=~'$namespace'})) / avg by (workload_name, namespace) (groundcover_container_cpu_limit_m_cpu{node_name=~'$node', namespace=~'$namespace'})))",
       "legendFormat": "{{workload_name}}@{{namespace}}"
      }
     ]
    },
    {
     "title": "Most-utilizing workloads (CPU)",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 11, "x": 10, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, (avg by (workload_name, namespace) (rate(groundcover_container_m_cpu_usage_seconds_total{node_name=~'$node', namespace=~'$namespace'})) / avg by (workload_name, namespace) (groundcover_container_cpu_limit_m_cpu{node_name=~'$node', namespace=~'$namespace'})))",
       "legendFormat": "{{workload_name}}@{{namespace}}"
      }
     ]
    },
    {
     "title": "Under-utilizing workloads (Memory)",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 31 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "bottomk(10, (avg by (workload_name, namespace) (groundcover_container_mem_working_set_bytes{node_name=~'$node', namespace=~'$namespace'}) / avg by (workload_name, namespace) (groundcover_container_memory_limit_bytes{node_name=~'$node', namespace=~'$namespace'})))",
       "legendFormat": "{{workload_name}}@{{namespace}}"
      }
     ]
    },
    {
     "title": "Most-utilizing workloads (Memory)",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 11, "x": 10, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, (avg by (workload_name, namespace) (groundcover_container_mem_working_set_bytes{node_name=~'$node', namespace=~'$namespace'}) / avg by (workload_name, namespace) (groundcover_container_memory_limit_bytes{node_name=~'$node', namespace=~'$namespace'})))",
       "legendFormat": "{{workload_name}}@{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Efficiency ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory Utilization",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg (groundcover_container_mem_working_set_bytes{node_name=~'$node'}) / avg (groundcover_container_memory_limit_bytes{node_name=~'$node'})"
      }
     ]
    },
    {
     "title": "CPU Utilization",
     "type": "gauge",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg(rate(groundcover_container_m_cpu_usage_seconds_total{node_name=~'$node'}) / groundcover_container_cpu_limit_m_cpu{node_name=~'$node'})"
      }
     ]
    },
    {
     "title": "Potential CPU consumption (Cores)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "mCPU" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(groundcover_container_cpu_limit_m_cpu{node_name=~'$node'})"
      }
     ]
    },
    {
     "title": "Potential Memory consumption (GB)",
     "type": "stat",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(groundcover_container_memory_limit_bytes{node_name=~'$node'})"
      }
     ]
    }
   ]
  },
  {
   "title": "Stability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spikiest workloads (CPU)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 7, "x": 0, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, (stddev(rate(groundcover_container_m_cpu_usage_seconds_total{node_name=~'$node', namespace=~'$namespace'})) by (workload_name, namespace) / avg(rate(groundcover_container_m_cpu_usage_seconds_total{node_name=~'$node', namespace=~'$namespace'})) by (workload_name, namespace)))",
       "legendFormat": "{{workload_name}}@{{namespace}}"
      }
     ]
    },
    {
     "title": "Spikiest Workloads (Mem)",
     "type": "bargauge",
     "gridPos": { "h": 8, "w": 10, "x": 7, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10,(stddev(groundcover_container_mem_working_set_bytes{node_name=~'$node', namespace=~'$namespace'}) by (workload_name,namespace) / avg(groundcover_container_mem_working_set_bytes{node_name=~'$node', namespace=~'$namespace'}) by (workload_name,namespace)))",
       "legendFormat": "{{workload_name}}@{{namespace}}"
      }
     ]
    },
    {
     "title": "kube-system events",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 11, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum by (workload_name) (groundcover_resource_total_counter{type=\"container_state\",namespace=\"kube-system\"})",
       "legendFormat": "{{workload_name}}"
      }
     ]
    }
   ]
  }
 ]
}