{
 "title": "Workload Overview Dashboard",
 "description": "Example of Groundcover's PromQL Datasource Powers",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prom", "label": "cluster", "query": "prometheus" },
   {
    "name": "related_workloads",
    "query": {
     "query": "label_values({__name__=~\"groundcover_.*_total_counter\", namespace='$namespace', workload_name='$workload'}, remote_service_name)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(groundcover_resource_total_counter{type=\"container_info\"}, namespace)"
    }
   },
   {
    "name": "workload",
    "query": {
     "query": "label_values(groundcover_resource_total_counter{namespace='$namespace', type=\"container_info\"}, workload_name)"
    }
   },
   { "name": "ds_sql", "query": "postgres" },
   { "name": "ds_logs", "query": "loki" }
  ]
 },
 "panels": [
  {
   "title": "Deployed Images",
   "type": "table",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "count(groundcover_resource_total_counter{namespace='$namespace', workload_name='$workload',type=\"container_info\"}) by (container_name, container_image)",
     "legendFormat": "{{container_image}}"
    }
   ]
  },
  {
   "title": "Num of Pods",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(groundcover_resource_total_counter{namespace='$namespace', workload_name='$workload', type=\"container_info\"}) by (pod_name))"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mCPU" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(groundcover_cpu_usage_m_cpu{namespace='$namespace', workload_name='$workload'})"
    }
   ]
  },
  {
   "title": "Memory ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(groundcover_resident_set_size_bytes{namespace='$namespace', workload_name='$workload'})"
    }
   ]
  },
  {
   "title": "Detected Protocols",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(groundcover_resource_total_counter{type=\"http\",namespace='$namespace', workload_name='$workload'}[$__rate_interval]))",
     "legendFormat": "HTTP"
    },
    {
     "expr": "sum(rate(groundcover_resource_total_counter{type=\"kafka\", namespace='$namespace', workload_name='$workload'}[$__rate_interval]))",
     "legendFormat": "Kafka"
    },
    {
     "expr": "sum(rate(groundcover_resource_total_counter{type=\"grpc\",namespace='$namespace', workload_name='$workload'}[$__rate_interval]))",
     "legendFormat": "GRPC"
    }
   ]
  },
  {
   "title": "Success Rate",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "clamp(sum(increase(groundcover_resource_success_counter{namespace='$namespace', workload_name='$workload'}[$__range])) / sum(increase(groundcover_resource_total_counter{namespace='$namespace', workload_name='$workload'}[$__range])),0,1)"
    }
   ]
  },
  {
   "title": "Latency P50",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(groundcover_resource_latency_seconds{type=~\"postgres|mysql|http|grpc\", namespace='$namespace', workload_name='$workload', role=\"server\", quantile=\"0.50\"})"
    }
   ]
  },
  {
   "title": "Latency P99",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(groundcover_resource_latency_seconds{type=~\"postgres|mysql|http|grpc\", namespace='$namespace', workload_name='$workload', role=\"server\", quantile=\"0.99\"})"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "alias(sum(rate(groundcover_resource_error_counter{namespace='$namespace', workload_name='$workload', type=~\"http|grpc\"}[$__rate_interval])), 'HTTP/GRPC')"
    },
    {
     "expr": "alias(sum(rate(groundcover_resource_error_counter{namespace='$namespace', workload_name='$workload', type=\"dns\"}[$__rate_interval])), 'DNS')"
    }
   ]
  },
  {
   "title": "CPU / Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 19, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "mCPU" } },
     "targets": [
      {
       "expr": "sum(groundcover_cpu_usage_m_cpu{namespace='$namespace', workload_name='$workload'})",
       "legendFormat": "utilisation"
      },
      {
       "expr": "sum(groundcover_cpu_limit_m_cpu{namespace='$namespace', workload_name='$workload'})",
       "legendFormat": "limit"
      },
      {
       "expr": "sum(groundcover_cpu_request_m_cpu{namespace='$namespace', workload_name='$workload'})",
       "legendFormat": "request"
      }
     ]
    },
    {
     "title": "CPU Utilization by Container",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "mCPU" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, (avg (groundcover_cpu_usage_m_cpu{namespace='$namespace', workload_name='$workload'}) by (container_name)))"
      }
     ]
    },
    {
     "title": "Memory Utilisation",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 19, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(groundcover_resident_set_size_bytes{namespace='$namespace', workload_name='$workload'})",
       "legendFormat": "utilisation"
      },
      {
       "expr": "sum(groundcover_memory_limit_bytes{namespace='$namespace', workload_name='$workload'})",
       "legendFormat": "limit"
      },
      {
       "expr": "sum(groundcover_memory_request_bytes{namespace='$namespace', workload_name='$workload'})",
       "legendFormat": "request"
      }
     ]
    },
    {
     "title": "Memory Utilisation by Container",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, avg(groundcover_resident_set_size_bytes{namespace='$namespace', workload_name='$workload'}) by (container_name))"
      }
     ]
    }
   ]
  },
  {
   "title": "Related Workloads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Errors by Related Workload",
     "type": "stat",
     "gridPos": { "h": 13, "w": 17, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(rate(groundcover_resource_error_counter{namespace='$namespace', workload_name=~'$related_workloads'}[$__rate_interval])) by(workload_name)",
       "legendFormat": "{{workload_name}}"
      }
     ]
    },
    {
     "title": "Top Related Workloads",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 7, "x": 17, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, (sum(rate(groundcover_resource_total_counter{type=\"http\", namespace='$namespace', workload_name='$workload'}[$__rate_interval])) by (remote_service_name) != 0))",
       "legendFormat": "{{remote_service_name}} (HTTP)"
      },
      {
       "expr": "topk(5, (sum(rate(groundcover_resource_total_counter{type=~\"postgresql|mysql\", namespace='$namespace', workload_name='$workload'}[$__rate_interval])) by (dialect, remote_service_name) != 0))",
       "legendFormat": "{{remote_service_name}} ({{dialect}})"
      },
      {
       "expr": "topk(3, (sum(rate(groundcover_resource_total_counter{type=\"dns\", namespace='$namespace', workload_name='$workload'}[$__rate_interval])) by (remote_addr) != 0))",
       "legendFormat": "{{remote_addr}} (DNS)"
      },
      {
       "expr": "topk(10, (sum(rate(groundcover_resource_total_counter{type=\"grpc\", namespace='$namespace', workload_name='$workload'}[$__rate_interval])) by (remote_service_name) != 0))",
       "legendFormat": "{{remote_service_name}} (GRPC)"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests by Status Code",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate (groundcover_resource_total_counter{type=~\"http|grpc\", namespace='$namespace', workload_name='$workload'}[$__rate_interval])) by (response_status_code)"
      }
     ]
    },
    {
     "title": "Error Rate as Server",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 17, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(groundcover_resource_error_counter{type=~\"http|grpc\", namespace='$namespace', workload_name='$workload', role=\"server\"}[$__rate_interval])) by (remote_service_name)",
       "legendFormat": "{{remote_service_name}} (client)"
      }
     ]
    },
    {
     "title": "Top Served APIs",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, (sum(rate(groundcover_resource_total_counter{type=~\"http|grpc\", namespace='$namespace', workload_name='$workload', role=\"server\"}[$__rate_interval])) by (clustered_path) != 0))"
      }
     ]
    },
    {
     "title": "Error Rate as Client",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 17, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(groundcover_resource_error_counter{type=~\"http|grpc\", namespace='$namespace', workload_name='$workload', role=\"client\"}[$__rate_interval])) by (remote_service_name)"
      }
     ]
    },
    {
     "title": "Top Outgoing APIs",
     "type": "bargauge",
     "gridPos": { "h": 9, "w": 7, "x": 17, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, (sum(rate(groundcover_resource_total_counter{type=~\"http|grpc\", namespace='$namespace', workload_name='$workload', role=\"client\"}[$__rate_interval])) by (clustered_path) != 0))"
      }
     ]
    },
    {
     "title": "Error Rate by API",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 17, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(groundcover_resource_error_counter{type=~\"http|grpc\", namespace='$namespace', workload_name='$workload'}[$__rate_interval])) by (clustered_path)"
      }
     ]
    },
    {
     "title": "Slowest APIs",
     "type": "bargauge",
     "gridPos": { "h": 21, "w": 7, "x": 17, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, (avg(groundcover_resource_latency_seconds{type=~\"http|grpc\", namespace='$namespace', workload_name='$workload', quantile=\"0.50\"}) by (clustered_path) != 0))"
      }
     ]
    },
    {
     "title": "Latency by API",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 17, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(25, avg(groundcover_resource_latency_seconds{type=~\"http|grpc\", namespace='$namespace', workload_name='$workload', quantile=\"0.50\"}) by (clustered_path))"
      }
     ]
    }
   ]
  },
  {
   "title": "SQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency by SQL Server",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 13, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(20, avg(groundcover_resource_latency_seconds{type=~\"postgresql|mysql\", namespace='$namespace', workload_name='$workload', role=\"client\", quantile=\"0.50\"}) by (remote_service_name))"
      }
     ]
    },
    {
     "title": "Slowest Queries",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 11, "x": 13, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, avg (groundcover_resource_latency_seconds{type=~\"postgresql|mysql\", namespace='$namespace', workload_name='$workload', role=\"client\", quantile=\"0.50\"}) by (query_id))"
      },
      {
       "rawSql": "SELECT\n  r.attributes->>'db.operation' as query_id,\n  r.attributes->>'query_fingerprint' as query_fingerprint\nFROM _ps_trace.resource as r\nJOIN _ps_trace.span_entities s\n  ON r.hash_id = s.resource_hash\nWHERE (s.product_type = 'postgresql' OR s.product_type = 'mysql')\n  AND s.name LIKE '$workload'\n  AND s.namespace LIKE '$namespace'\ngroup by 1,2"
      }
     ]
    },
    {
     "title": "Query Rate by Server",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 13, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "topk(20, sum(rate(groundcover_resource_total_counter{type=~\"postgresql|mysql\", namespace='$namespace', workload_name='$workload', role=\"client\"}[$__rate_interval])) by (remote_service_name))"
      }
     ]
    },
    {
     "title": "Most Common Queries",
     "type": "bargauge",
     "gridPos": { "h": 10, "w": 11, "x": 13, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "topk(10, sort_desc(sum (rate(groundcover_resource_total_counter{type=~\"postgresql|mysql\", namespace='$namespace', workload_name='$workload'})) by (query_id) != 0))"
      },
      {
       "rawSql": "SELECT\n  r.attributes->>'db.operation' as query_id,\n  r.attributes->>'query_fingerprint' as query_fingerprint\nFROM _ps_trace.resource as r\nJOIN _ps_trace.span_entities s\n  ON r.hash_id = s.resource_hash\nWHERE (s.product_type = 'postgresql' OR s.product_type = 'mysql')\n  AND s.name LIKE '$workload'\n  AND s.namespace LIKE '$namespace'\ngroup by 1,2"
      }
     ]
    },
    {
     "title": "Error Rate by Server",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 13, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(groundcover_resource_error_counter{type=~\"postgresql|mysql\", namespace='$namespace', workload_name='$workload', role=\"client\"}[$__rate_interval])) by (remote_service_name)"
      }
     ]
    },
    {
     "title": "Response Size by Server",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 11, "x": 13, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(groundcover_resp_size_bytes{type=~\"postgresql|mysql\", namespace='$namespace', workload_name='$workload', role=\"client\"}[$__rate_interval])) by (remote_service_name)"
      }
     ]
    }
   ]
  },
  {
   "title": "DNS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Latency by Server",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 19, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "topk(20, avg by (remote_addr) (groundcover_resource_latency_seconds{type=\"dns\", namespace='$namespace', workload_name='$workload', role=\"client\", quantile=\"0.50\"}))"
      }
     ]
    },
    {
     "title": "Query Types",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 90 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (query_type) (groundcover_resource_total_counter{type=\"dns\", namespace='$namespace', workload_name='$workload', role=\"client\"})"
      }
     ]
    },
    {
     "title": "Error Rate by Type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 19, "x": 0, "y": 100 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum by (response_return_code) (rate(groundcover_resource_error_counter{type=\"dns\", namespace='$namespace', workload_name='$workload', role=\"client\" ,response_return_code!=\"NoError\"}[$__rate_interval]))"
      }
     ]
    },
    {
     "title": "Return Codes",
     "type": "piechart",
     "gridPos": { "h": 10, "w": 5, "x": 19, "y": 100 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (response_return_code) (groundcover_resource_total_counter{type=\"dns\", namespace='$namespace', workload_name='$workload', role=\"client\"})"
      }
     ]
    }
   ]
  }
 ]
}