{{- range $key,$value := .Values.nodePools }}
{{- if (ne $value.enabled false)}}
---
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: {{ $key }}
spec:
  disruption:
  {{- if $value.disruption }}
  {{- with $value.disruption }}
    consolidateAfter: {{ default "5m" .consolidateAfter }}
    consolidationPolicy: {{ default "WhenEmptyOrUnderutilized" .consolidationPolicy }}
    budgets: {{ default (list (dict "nodes" "10%" "reasons"  (list "Empty" "Drifted" "Underutilized"))) .budgets | toYaml | nindent 4 }}
  {{- end }}
  {{- else }}
    consolidateAfter: "5m" 
    consolidationPolicy: "WhenEmptyOrUnderutilized" 
    budgets: 
    - nodes: 10%
      reasons:
      - Empty
      - Drifted
      - Underutilized
  {{- end }}
  limits:
  {{- if $value.limits }}
  {{- with $value.limits }}
    cpu: {{ default "1000" .cpu }}
    memory: {{ default "3000Gi" .memory }}
  {{- end }}
  {{- else }}
    cpu: "1000" 
    memory: "3000Gi"
  {{- end }}
  {{- if $value.weight }}
  weight: {{ $value.weight }}
  {{- end }}
  template: {{if or $value.nodeLabels $value.nodeAnnotations }}
    metadata: 
      {{- with $value.nodeLabels }}
      labels: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with $value.nodeAnnotations }}
      annotations: {{ toYaml . | nindent 8 }}
      {{- end }}
    {{- end }}
    spec:
      {{- with $value.taints }}
      taints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $value.startupTaints }}
      startupTaints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      expireAfter: {{ default "Never" $value.expireAfter }}
      terminationGracePeriod: {{ default "1h" $value.terminationGracePeriod }}
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: {{ $value.ec2NodeClass }}
      requirements: 
      {{- if $value.instanceCategories.values }}
      {{- with $value.instanceCategories }}
      - key: "karpenter.k8s.aws/instance-category"
        operator: {{ default "In" .operator }}
        values: {{- range default (list "c" "m" "r") .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- else }}
      - key: "karpenter.k8s.aws/instance-category"
        operator: "In"
        values: ["c", "m", "r"]
      {{- end }}
      {{- if $value.instanceFamily.values }}
      {{- with $value.instanceFamily }}
      - key: "karpenter.k8s.aws/instance-family"
        operator: {{ default "In" .operator }}
        values: {{- range .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.instanceCpu.values }}
      {{- with $value.instanceCpu }}
      - key: "karpenter.k8s.aws/instance-cpu"
        operator: {{ default "Gt" .operator}}
        values: {{- range .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.instanceHypervisor.values }}
      {{- with $value.instanceHypervisor }}
      - key: "karpenter.k8s.aws/instance-hypervisor"
        operator: {{ default "In" .operator }}
        values: {{- range default (list "nitro") .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- else }}
      - key: "karpenter.k8s.aws/instance-hypervisor"
        operator: "In" 
        values: ["nitro"]
      {{- end }}
      {{- if $value.instanceGeneration.values }}
      {{- with $value.instanceGeneration }}
      - key: "karpenter.k8s.aws/instance-generation"
        operator: {{ default "Gt" .operator }}
        values: {{- range default (list "5") .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- else }}
      - key: "karpenter.k8s.aws/instance-generation"
        operator: "Gt"
        values: ["5"]
      {{- end }}
      {{- if $value.instanceZone.values }}
      {{- with $value.instanceZone }}
      - key: "topology.kubernetes.io/zone"
        operator: {{ default "In" .operator }}
        values: {{- range .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.instanceArch.values }}
      {{- with $value.instanceArch }}
      - key: "kubernetes.io/arch"
        operator: {{ default "In" .operator }}
        values: {{- range default (list "amd64") .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- else }}
      - key: "kubernetes.io/arch"
        operator: "In" 
        values: ["amd64"]
      {{- end }}
      {{- if $value.capacityType.values }}
      {{- with $value.capacityType }}
      - key: "karpenter.sh/capacity-type"
        operator: {{ default "In" .operator }}
        values: {{- range default (list "on-demand") .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- else }}
      - key: "karpenter.sh/capacity-type"
        operator: "In"
        values: ["on-demand"]
      {{- end }}
      {{- if $value.instanceMemory.values }}
      {{- with $value.instanceMemory }}
      - key: "karpenter.k8s.aws/instance-memory"
        operator: {{ default "Gt" .operator}}
        values: {{- range .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.instanceType.values }}
      {{- with $value.instanceType }}
      - key: "node.kubernetes.io/instance-type"
        operator: {{ default "In" .operator }}
        values: {{- range .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.windowsBuild.values }}
      {{- with $value.windowsBuild }}
      - key: "node.kubernetes.io/windows-build"
        operator: {{ default "In" .operator }}
        values: {{- range .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.os.values }}
      {{- with $value.os }}
      - key: "kubernetes.io/os"
        operator: {{ default "In" .operator }}
        values: {{- range .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.encryptionInTransit.values }}
      {{- with $value.encryptionInTransit }}
      - key: "karpenter.k8s.aws/instance-encryption-in-transit-supported"
        operator: {{ default "In" .operator }}
        values: {{- range .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.size.values }}
      {{- with $value.size }}
      - key: "karpenter.k8s.aws/instance-size"
        operator: {{ default "In" .operator }}
        values: {{- range .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.cpuManufacturer.values }}
      {{- with $value.cpuManufacturer }}
      - key: "karpenter.k8s.aws/instance-cpu-manufacturer"
        operator: {{ default "In" .operator }}
        values: {{- range .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.ebsBandwith.values }}
      {{- with $value.ebsBandwith }}
      - key: "karpenter.k8s.aws/instance-ebs-bandwidth"
        operator: {{ default "In" .operator }}
        values: {{- range .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.networkBandwith.values }}
      {{- with $value.networkBandwith }}
      - key: "karpenter.k8s.aws/instance-network-bandwidth"
        operator: {{ default "In" .operator }}
        values: {{- range .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.pods.values }}
      {{- with $value.pods }}
      - key: "karpenter.k8s.aws/instance-pods"
        operator: {{ default "In" .operator }}
        values: {{- range .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.gpuName.values }}
      {{- with $value.gpuName }}
      - key: "karpenter.k8s.aws/instance-gpu-name"
        operator: {{ default "In" .operator }}
        values: {{- range .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.gpuManufacturer.values }}
      {{- with $value.gpuManufacturer }}
      - key: "karpenter.k8s.aws/instance-gpu-manufacturer"
        operator: {{ default "In" .operator }}
        values: {{- range .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.gpuCount.values }}
      {{- with $value.gpuCount }}
      - key: "karpenter.k8s.aws/instance-gpu-count"
        operator: {{ default "In" .operator }}
        values: {{- range .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.gpuMemory.values }}
      {{- with $value.gpuMemory }}
      - key: "karpenter.k8s.aws/instance-gpu-memory"
        operator: {{ default "In" .operator }}
        values: {{- range .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
      {{- if $value.localNvme.values }}
      {{- with $value.localNvme }}
      - key: "karpenter.k8s.aws/instance-local-nvme"
        operator: {{ default "In" .operator }}
        values: {{- range .values }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
      {{- end }}
{{- end }}
{{- end }}