{{ if .Values.agent.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.agent.additionalAnnotations }}
{{ toYaml .Values.agent.additionalAnnotations | indent 4 }}
    {{- end }}
  name: alligator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    app: alligator
    app.kubernetes.io/name: alligator
    {{- if .Values.agent.additionalLabels }}
{{ toYaml .Values.agent.additionalLabels | indent 4 }}
    {{- end }}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: alligator
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ (include "agent.monitoring.port" .) | quote }}
        vm.io/path: "vmetrics"
        vm.io/port: {{ (include "agent.monitoring.port" .) | quote  }}
        groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
        checksum/tracy_config: {{ include (print $.Template.BasePath "/agent/config/tracy/config.yaml") . | sha256sum }}
        checksum/alligator_config: {{ include (print $.Template.BasePath "/agent/config/alligator/config.yaml") . | sha256sum }}
        {{- if .Values.agent.additionalAnnotations }}
{{ toYaml .Values.agent.additionalAnnotations | indent 8 }}
        {{- end }}
        {{- if .Values.agent.podAnnotations }}
{{ toYaml .Values.agent.podAnnotations | indent 8 }}
        {{- end }}
      labels:
        app: alligator
        app.kubernetes.io/name: alligator
        {{- include "groundcover.labels" . | nindent 8 }}
        {{- if .Values.agent.additionalLabels }}
{{ toYaml .Values.agent.additionalLabels | indent 8 }}
        {{- end }}
        {{- if .Values.agent.podLabels }}
{{ toYaml .Values.agent.podLabels | indent 8 }}
        {{- end }}
    spec:
      imagePullSecrets: {{ include "imagePullSecrets" . }}
{{- if .Values.agent.tolerations }}
      tolerations:
{{ toYaml .Values.agent.tolerations | indent 8 }}
{{- end }}
{{- if .Values.agent.affinity }}
      affinity:
{{ toYaml .Values.agent.affinity | indent 8 }}
{{- end }}
{{- if .Values.agent.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.agent.nodeSelector | indent 8 }}
{{- end }}
      containers:
{{- if eq (include "telemetry.enabled" .) "true" }}
        - name: fluent-bit
          image: {{ tpl .Values.agent.flb.image.repository . }}:{{ .Values.agent.flb.image.tag }}
          ports:
            - name: http
              containerPort: 2020
              protocol: TCP
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/custom_parsers.conf
              subPath: custom_parsers.conf
            - name: docker
              readOnly: true
              mountPath: /var/lib/docker/containers
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: GC_GROUNDCOVERVERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['groundcover_version']   
            - name: GC_RUNNINGNAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GC_CLUSTERID
              valueFrom:
                secretKeyRef:
                    name: groundcover-config
                    key: GC_CLUSTER_ID
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  key: {{ template "groundcover.apikeySecretKey" . }}
                  name: {{ template "groundcover.apikeySecretName" . }}
          resources:
            {{- toYaml .Values.agent.flb.resources | nindent 12 }}
{{- end }}
        - env:
            - name: PROMETHEUS_PORT
              value: {{ (include "agent.monitoring.port" .) | quote }}
            - name: FLORA_PROMETHEUSSERVER_ENABLED
              value: "false"
            - name: FLORA_NATTRACKER_PROCMOUNTPATH
              value: "/host/proc"
            - name: FLORA_SYSTEMWATCHER_PROCMOUNTPATH
              value: "/host/proc"
            - name: FLORA_SYSTEMWATCHER_HOSTMOUNTPATH
              value: "/host"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name                  
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName              
            - name: GC_RUNNINGNAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GC_CLUSTERID
              valueFrom:
                secretKeyRef:
                    name: groundcover-config
                    key: GC_CLUSTER_ID
            - name: GC_REGION
              valueFrom:
                secretKeyRef:
                    name: groundcover-config
                    key: GC_REGION
            - name: GC_GROUNDCOVERVERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['groundcover_version']
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  key: {{ template "groundcover.apikeySecretKey" . }}
                  name: {{ template "groundcover.apikeySecretName" . }}        
            {{- with .Values.agent.alligator.env }}
              {{ toYaml . | nindent 12 }}
            {{- end }}                                
          image: {{ tpl .Values.agent.alligator.image.repository . }}:{{ default .Chart.AppVersion .Values.global.origin.tag }}
          resources:
{{- toYaml .Values.agent.alligator.resources | nindent 12 }}
          imagePullPolicy: Always
          name: alligator
          ports:
            - containerPort: {{ (include "agent.monitoring.port" .) | int }}
              name: prom-metrics
              protocol: TCP
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
                - SYS_ADMIN
            privileged: true
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - mountPath: /host
              name: host-root
              readOnly: true
            - mountPath: /sys
              name: sys
              readOnly: true
            - mountPath: /config
              name: alligator-configuration
              readOnly: false
            - mountPath: /scrape-config
              name: alligator-scrape-configuration
              readOnly: false
            - mountPath: /comm
              name: comm
              readOnly: false
            - mountPath: /var/run/positions
              name: alligator-position
            - mountPath: /var/lib/docker/containers
              name: docker
              readOnly: true
{{- if eq (include "agent.tracy.enabled" .) "true" }}
        - env:
            - name: PL_HOST_PATH
              value: /host
            - name: NNMSG_LISTENING_ADDRESS
              value: ipc:///comm/tracy.data
            - name: KTARGET_DATA_BYTES_PER_SEC
              value: "104857600"
            - name: KTARGET_CONTROL_BYTES_PER_SEC
              value: "5242880"
        {{- with .Values.agent.tracy.env }}
          {{ toYaml . | nindent 12 }}
        {{- end }}
          envFrom:
            - configMapRef:
                name: tracy-conf-fg9h4chctk
          image: {{ tpl .Values.agent.tracy.image.repository . }}:latest
          resources:
{{- toYaml .Values.agent.tracy.resources | nindent 12 }}
          imagePullPolicy: Always
          name: tracy
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
                - SYS_ADMIN
            privileged: true
          volumeMounts:
            - mountPath: /host
              name: host-root
              readOnly: true
            - mountPath: /sys
              name: sys
              readOnly: true
            - mountPath: /comm
              name: comm
              readOnly: false
            - mountPath: /linux-headers
              name: linux-headers
              readOnly: true
{{- end }}
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: {{ default false .Values.agent.hostNetwork }}
      hostPID: true
      initContainers:
        - name: check-opentelemetry-collector-ready
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  key: {{ template "groundcover.apikeySecretKey" . }}
                  name: {{ template "groundcover.apikeySecretName" . }}        
          args:
          - while [ $(curl -H "apikey:$API_KEY" -skw '%{http_code}' {{ include "opentelemetry-collector.health.http.url" . }}
            -o /dev/null) -ne 200 ]; do echo 'Waiting for opentelemetry-collector...'; sleep 2; done; echo opentelemetry-collector is up
          command:
            - /bin/sh
            - -c
          image: '{{ printf "%s/curl:latest" .Values.global.origin.registry }}'
        - name: check-metrics-ingestor-ready
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  key: {{ template "groundcover.apikeySecretKey" . }}
                  name: {{ template "groundcover.apikeySecretName" . }}   
          args:
          - while [ $(curl -H "apikey:$API_KEY" -ksw '%{http_code}' {{ include "metrics-ingester.health.http.url" . }} -o /dev/null) -ne 200 ]; do echo 'Waiting for VictoriaMetrics Agent...'; sleep 2; done; echo VictoriaMetrics Agent is up
          command:
            - /bin/sh
            - -c
          image: curlimages/curl:latest
      serviceAccountName: alligator
{{- if .Values.agent.priorityClassName }}
      priorityClassName: {{ .Values.agent.priorityClassName }}
{{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
{{- if eq (include "telemetry.enabled" .) "true" }}
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
            defaultMode: 420
{{- end }}
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - hostPath:
            path: /
            type: Directory
          name: host-root
        - hostPath:
            path: /sys
            type: Directory
          name: sys
        - configMap:
            defaultMode: 420
            name: alligator-configuration
          name: alligator-configuration
        - configMap:
            defaultMode: 420
            name: alligator-scrape-configuration
          name: alligator-scrape-configuration
        - emptyDir: {}
          name: comm
        - hostPath:
            path: /run/alligator-position-{{ .Release.Namespace }}
          name: alligator-position
        - hostPath:
            path: /var/lib/docker/containers
          name: docker
        - emptyDir: {}
          name: linux-headers
        - hostPath:
            path: /var/log
          name: varlog
{{- end }}
