{{ if .Values.global.agent.enabled }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.agent.additionalAnnotations }}
{{ toYaml .Values.agent.additionalAnnotations | indent 4 }}
    {{- end }}
  name: alligator
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    app: alligator
    app.kubernetes.io/name: alligator
    {{- if .Values.agent.additionalLabels }}
{{ toYaml .Values.agent.additionalLabels | indent 4 }}
    {{- end }}
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%
  selector:
    matchLabels:
      app: alligator
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: {{ (include "agent.monitoring.port" .) | quote }}
        vm.io/path: "vmetrics"
        vm.io/port: {{ (include "agent.monitoring.port" .) | quote  }}
        groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
        checksum/alligator_config: {{ include (print $.Template.BasePath "/agent/config/alligator/config.yaml") . | sha256sum }}
        {{- if .Values.agent.additionalAnnotations }}
{{ toYaml .Values.agent.additionalAnnotations | indent 8 }}
        {{- end }}
        {{- if .Values.agent.podAnnotations }}
{{ toYaml .Values.agent.podAnnotations | indent 8 }}
        {{- end }}
      labels:
        app: alligator
        app.kubernetes.io/name: alligator
        {{- include "groundcover.labels" . | nindent 8 }}
        {{- if .Values.agent.additionalLabels }}
{{ toYaml .Values.agent.additionalLabels | indent 8 }}
        {{- end }}
        {{- if .Values.agent.podLabels }}
{{ toYaml .Values.agent.podLabels | indent 8 }}
        {{- end }}
    spec:
      imagePullSecrets: {{ include "imagePullSecrets" . }}
{{- if .Values.agent.tolerations }}
      tolerations:
{{ toYaml .Values.agent.tolerations | indent 8 }}
{{- end }}
{{- if .Values.agent.affinity }}
      affinity:
{{ toYaml .Values.agent.affinity | indent 8 }}
{{- end }}
{{- if .Values.agent.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.agent.nodeSelector | indent 8 }}
{{- end }}
      containers:
        - env:
            - name: PROMETHEUS_PORT
              value: {{ (include "agent.monitoring.port" .) | quote }}
            - name: FLORA_PROMETHEUSSERVER_ENABLED
              value: "false"
            - name: FLORA_NATTRACKER_PROCMOUNTPATH
              value: "/host/proc"
            - name: FLORA_SYSTEMWATCHER_PROCMOUNTPATH
              value: "/host/proc"
            - name: FLORA_SYSTEMWATCHER_HOSTMOUNTPATH
              value: "/host"
            - name: FLORA_NETWORKTRACER_CONNECTIONMANAGER_PROTOCOLS_HTTP_UNLIMITEDPAYLOADENDPOINTS
              value: {{ (tpl .Values.agent.alligator.httpUnlimitedEndpoints .) | quote }}
            - name: FLORA_NETWORKTRACER_CONNECTIONMANAGER_PROTOCOLS_HTTP2_UNLIMITEDPAYLOADENDPOINTS
              value: {{ (tpl .Values.agent.alligator.http2UnlimitedEndpoints .) | quote }}
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name                  
            - name: HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName              
            - name: GC_RUNNINGNAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GC_CLUSTERID
              valueFrom:
                secretKeyRef:
                    name: groundcover-config
                    key: GC_CLUSTER_ID
            - name: GC_REGION
              valueFrom:
                secretKeyRef:
                    name: groundcover-config
                    key: GC_REGION
            - name: GC_GROUNDCOVERVERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['groundcover_version']
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  key: {{ template "groundcover.apikeySecretKey" . }}
                  name: {{ template "groundcover.apikeySecretName" . }}      
            - name: NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            {{- with .Values.agent.alligator.env }}
              {{ toYaml . | nindent 12 }}
            {{- end }}                                
          image: {{ tpl .Values.agent.alligator.image.repository . }}:{{ default .Chart.AppVersion .Values.global.origin.tag }}
          resources:
{{- toYaml .Values.agent.alligator.resources | nindent 12 }}
          imagePullPolicy: Always
          name: alligator
          ports:
            - containerPort: {{ (include "agent.monitoring.port" .) | int }}
              name: prom-metrics
              protocol: TCP
            - containerPort: {{ .Values.agent.alligator.apmIngestor.dataDog.tracesPort }}
              name: dd-traces
              protocol: TCP
            {{- if and .Values.agent.alligator.apmIngestor.otel.direct.zipkin.enabled .Values.agent.alligator.apmIngestor.otel.direct.zipkin.port}}
            - containerPort: {{ .Values.agent.alligator.apmIngestor.otel.direct.zipkin.port }}
              name: zipkin
              protocol: TCP
            {{- end }}
            {{- if and .Values.agent.alligator.apmIngestor.otel.direct.otlp.enabled .Values.agent.alligator.apmIngestor.otel.direct.otlp.grpcPort}}
            - containerPort: {{ .Values.agent.alligator.apmIngestor.otel.direct.otlp.grpcPort }}
              name: otlp-grpc
              protocol: TCP
            {{- end }}
            {{- if and .Values.agent.alligator.apmIngestor.otel.direct.otlp.enabled .Values.agent.alligator.apmIngestor.otel.direct.otlp.httpPort}}
            - containerPort: {{ .Values.agent.alligator.apmIngestor.otel.direct.otlp.httpPort }}
              name: otlp-http
              protocol: TCP
            {{- end }}
            {{- if and .Values.agent.alligator.apmIngestor.otel.direct.jaeger.enabled .Values.agent.alligator.apmIngestor.otel.direct.jaeger.grpcPort}}
            - containerPort: {{ .Values.agent.alligator.apmIngestor.otel.direct.jaeger.grpcPort }}
              name: jaeger-grpc
              protocol: TCP     
            {{- end }}
            {{- if and .Values.agent.alligator.apmIngestor.otel.direct.jaeger.enabled .Values.agent.alligator.apmIngestor.otel.direct.jaeger.thriftHttpPort}}
            - containerPort: {{ .Values.agent.alligator.apmIngestor.otel.direct.jaeger.thriftHttpPort }}
              name: jaeger-th-http
              protocol: TCP     
            {{- end }}
            {{- if and .Values.agent.alligator.apmIngestor.otel.direct.jaeger.enabled .Values.agent.alligator.apmIngestor.otel.direct.jaeger.thriftBinaryPort}}
            - containerPort: {{ .Values.agent.alligator.apmIngestor.otel.direct.jaeger.thriftBinaryPort }}
              name: jaeger-th-bin
              protocol: UDP     
            {{- end }}
            {{- if and .Values.agent.alligator.apmIngestor.otel.direct.jaeger.enabled .Values.agent.alligator.apmIngestor.otel.direct.jaeger.thriftCompactPort}}
            - containerPort: {{ .Values.agent.alligator.apmIngestor.otel.direct.jaeger.thriftCompactPort }}
              name: jaeger-th-comp
              protocol: UDP     
            {{- end }}
          securityContext:
            capabilities:
              add:
                - SYS_PTRACE
                - SYS_ADMIN
            privileged: true
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - mountPath: /host
              name: host-root
              readOnly: true
            - mountPath: /sys
              name: sys
              readOnly: true
            - mountPath: /config
              name: alligator-configuration
              readOnly: false
            - mountPath: /scrape-config
              name: alligator-scrape-configuration
              readOnly: false
            - mountPath: /comm
              name: comm
              readOnly: false
            - mountPath: /var/run/positions
              name: alligator-position
            - mountPath: /var/lib/docker/containers
              name: docker
              readOnly: true
{{- if eq (include "telemetry.enabled" .) "true" }}
        - name: fluent-bit
          image: {{ tpl .Values.agent.flb.image.repository . }}:{{ .Values.agent.flb.image.tag }}
          ports:
            - name: http
              containerPort: 2020
              protocol: TCP
          volumeMounts:
            - name: varlog
              mountPath: /var/log
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/fluent-bit.conf
              subPath: fluent-bit.conf
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc/custom_parsers.conf
              subPath: custom_parsers.conf
            - name: docker
              readOnly: true
              mountPath: /var/lib/docker/containers
          livenessProbe:
            httpGet:
              path: /
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: http
              scheme: HTTP
            timeoutSeconds: 1
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          env:
            - name: GC_GROUNDCOVERVERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['groundcover_version']   
            - name: GC_RUNNINGNAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: GC_CLUSTERID
              valueFrom:
                secretKeyRef:
                    name: groundcover-config
                    key: GC_CLUSTER_ID
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  key: {{ template "groundcover.apikeySecretKey" . }}
                  name: {{ template "groundcover.apikeySecretName" . }}
        {{- with .Values.agent.flb.env }}
          {{ toYaml . | nindent 12 }}
        {{- end }}
          resources:
            {{- toYaml .Values.agent.flb.resources | nindent 12 }}
{{- end }}              
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: {{ default false .Values.agent.hostNetwork }}
      hostPID: true
      initContainers:
        - name: check-ingestion-endpoint-ready
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  key: {{ template "groundcover.apikeySecretKey" . }}
                  name: {{ template "groundcover.apikeySecretName" . }}        
          args:
          - | 
              while [ $(curl -H "apikey:$API_KEY" \
              {{- if .Values.global.ingestion.tls_skip_verify }}
                -k \
              {{- end }}
                -sw '%{http_code}' {{ include "ingestion.health.http.url" . }} -o /dev/null) -ne 200 ]
              do
                echo 'Waiting for ingestion endpoint...';
                sleep 2;
              done;
              echo ingestion endpoint is up
          command:
            - /bin/sh
            - -c
          image: '{{ printf "%s/curl:8.6.0" .Values.global.origin.registry }}'
        - name: check-metrics-ingestor-ready
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  key: {{ template "groundcover.apikeySecretKey" . }}
                  name: {{ template "groundcover.apikeySecretName" . }}   
          args:
          - |
              while [ $(curl -H "apikey:$API_KEY" \
              {{- if .Values.global.ingestion.tls_skip_verify }}
                -k \
              {{- end }}
                -sw '%{http_code}' {{ include "metrics-ingester.write.http.url" . }} -o /dev/null) -ne 204 ];
              do 
                echo 'Waiting for VictoriaMetrics Agent...'; 
                sleep 2; 
              done; 
              echo VictoriaMetrics Agent is up
          command:
            - /bin/sh
            - -c
          image: {{ printf "%s/curl:8.6.0" .Values.global.origin.registry }}
      serviceAccountName: alligator
{{- if or (.Values.agent.priorityClassName) (.Values.agent.priorityClass.create) }}
  {{- if .Values.agent.priorityClassName }}
      priorityClassName: {{ .Values.agent.priorityClassName }}
  {{- else }}
      priorityClassName: {{ include "groundcover.agentPriorityClass" . }}
  {{- end }}
{{- end }}
      terminationGracePeriodSeconds: 10
      volumes:
{{- if eq (include "telemetry.enabled" .) "true" }}
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
            defaultMode: 420
{{- end }}
        - name: varlibdockercontainers
          hostPath:
            path: /var/lib/docker/containers
        - hostPath:
            path: /
            type: Directory
          name: host-root
        - hostPath:
            path: /sys
            type: Directory
          name: sys
        - configMap:
            defaultMode: 420
            name: alligator-configuration
          name: alligator-configuration
        - configMap:
            defaultMode: 420
            name: alligator-scrape-configuration
          name: alligator-scrape-configuration
        - emptyDir: {}
          name: comm
        - hostPath:
            path: /run/alligator-position-{{ .Release.Namespace }}
          name: alligator-position
        - hostPath:
            path: /var/lib/docker/containers
          name: docker
        - emptyDir: {}
          name: linux-headers
        - hostPath:
            path: /var/log
          name: varlog
{{- end }}
