apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- if .Values.migrator.additionalLabels }}
{{ toYaml .Values.migrator.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ .Values.origin.tag }}
    {{- if .Values.migrator.additionalAnnotations }}
{{ toYaml .Values.migrator.additionalAnnotations | indent 4 }}
    {{- end }}
  name: migrator
  namespace: {{ .Release.Namespace }}
