{{ if .Values.global.agent.enabled }}
{{- if and (not .Values.agent.priorityClassName) .Values.agent.priorityClass.create }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ include "groundcover.agentPriorityClass" . }}
preemptionPolicy: {{ .Values.agent.priorityClass.preemptionPolicy }}
value: {{ .Values.agent.priorityClass.value }}
{{- end }}
{{- end }}