apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    {{- if .Values.agent.additionalLabels }}
{{ toYaml .Values.agent.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ .Values.origin.tag }}
    {{- if .Values.agent.additionalAnnotations }}
{{ toYaml .Values.agent.additionalAnnotations | indent 4 }}
    {{- end }}
  name: alligator
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - policy
  - extensions
  resourceNames:
  - {{ template "groundcover.fullname" . }}-alligator
  resources:
  - podsecuritypolicies
  verbs:
  - use
