{{ if .Values.global.agent.enabled }}
{{- $sensorValues := deepCopy .Values.agent.sensor -}}
{{- if .Values.agent.alligator -}}
{{ $sensorValues = mergeOverwrite $sensorValues .Values.agent.alligator }}
{{- end -}}
kind: Service
apiVersion: v1
metadata:
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.agent.additionalAnnotations }}
{{ toYaml .Values.agent.additionalAnnotations | indent 4 }}
    {{- end }}
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    app: sensor
    app.kubernetes.io/name: sensor
    {{- if .Values.agent.additionalLabels }}
{{ toYaml .Values.agent.additionalLabels | indent 4 }}
    {{- end }}
  name: {{ include "sensor.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: sensor
    app.kubernetes.io/part-of: '{{ include "groundcover.labels.partOf" . }}'
  ports:
  - protocol: TCP
    name: dd-traces
    port: {{ $sensorValues.apmIngestor.dataDog.tracesPort }}
    targetPort: {{ $sensorValues.apmIngestor.dataDog.tracesPort }}
  {{- if and $sensorValues.apmIngestor.otel.direct.zipkin.enabled $sensorValues.apmIngestor.otel.direct.zipkin.port $sensorValues.ingestionEnabled }}
  - protocol: TCP
    name: zipkin
    port: {{ $sensorValues.apmIngestor.otel.direct.zipkin.port }}
    targetPort: {{ $sensorValues.apmIngestor.otel.direct.zipkin.port }}
  {{- end }}
  {{- if and $sensorValues.apmIngestor.otel.direct.otlp.enabled $sensorValues.apmIngestor.otel.direct.otlp.grpcPort $sensorValues.ingestionEnabled }}
  - protocol: TCP
    name: otlp-grpc
    port: {{ $sensorValues.apmIngestor.otel.direct.otlp.grpcPort }}
    targetPort: {{ $sensorValues.apmIngestor.otel.direct.grpcPort }}
  {{- end }}
  {{- if and $sensorValues.apmIngestor.otel.direct.otlp.enabled $sensorValues.apmIngestor.otel.direct.otlp.httpPort $sensorValues.ingestionEnabled }}
  - protocol: TCP
    name: otlp-http
    port: {{ $sensorValues.apmIngestor.otel.direct.otlp.httpPort }}
    targetPort: {{ $sensorValues.apmIngestor.otel.direct.httpPort }}
  {{- end }}
  {{- if and $sensorValues.apmIngestor.otel.direct.jaeger.enabled $sensorValues.apmIngestor.otel.direct.jaeger.grpcPort $sensorValues.ingestionEnabled}}
  - protocol: TCP
    name: jeager-grpc
    port: {{ $sensorValues.apmIngestor.otel.direct.jaeger.grpcPort }}
    targetPort: {{ $sensorValues.apmIngestor.otel.direct.jaeger.grpcPort }}
  {{- end }}
  {{- if and $sensorValues.apmIngestor.otel.direct.jaeger.enabled $sensorValues.apmIngestor.otel.direct.jaeger.thriftHttpPort $sensorValues.ingestionEnabled}}
  - protocol: TCP
    name: jeager-thrift-http
    port: {{ $sensorValues.apmIngestor.otel.direct.jaeger.thriftHttpPort }}
    targetPort: {{ $sensorValues.apmIngestor.otel.direct.jaeger.thriftHttpPort }}
  {{- end }}
  {{- if and $sensorValues.apmIngestor.otel.direct.jaeger.enabled $sensorValues.apmIngestor.otel.direct.jaeger.thriftBinaryPort $sensorValues.ingestionEnabled}}
  - protocol: UDP
    name: jeager-thrift-binary
    port: {{ $sensorValues.apmIngestor.otel.direct.jaeger.thriftBinaryPort }}
    targetPort: {{ $sensorValues.apmIngestor.otel.direct.jaeger.thriftBinaryPort }}
  {{- end }}
  {{- if and $sensorValues.apmIngestor.otel.direct.jaeger.enabled $sensorValues.apmIngestor.otel.direct.jaeger.thriftCompactPort $sensorValues.ingestionEnabled}}
  - protocol: UDP
    name: jeager-thrift-compact
    port: {{ $sensorValues.apmIngestor.otel.direct.jaeger.thriftCompactPort }}
    targetPort: {{ $sensorValues.apmIngestor.otel.direct.jaeger.thriftCompactPort }}
  {{- end }}
  {{- if and $sensorValues.apmIngestor.otel.direct.httpjson.enabled $sensorValues.apmIngestor.otel.direct.httpjson.port $sensorValues.ingestionEnabled}}
  - protocol: TCP
    name: http-json
    port: {{ $sensorValues.apmIngestor.otel.direct.httpjson.port }}
    targetPort: {{ $sensorValues.apmIngestor.otel.direct.httpjson.port }}
  {{- end }}
  {{- if $sensorValues.setLocalTrafficPolicy }}
  internalTrafficPolicy: Local
  {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.agent.additionalAnnotations }}
{{ toYaml .Values.agent.additionalAnnotations | indent 4 }}
    {{- end }}
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    app: alligator
    app.kubernetes.io/name: alligator
    {{- if .Values.agent.additionalLabels }}
{{ toYaml .Values.agent.additionalLabels | indent 4 }}
    {{- end }}
  name: {{ include "alligator.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: {{ include "sensor.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
{{- if and $sensorValues.metricIngestor.serverEnabled $sensorValues.metricIngestor.serverPort $sensorValues.ingestionEnabled}}
---
kind: Service
apiVersion: v1
metadata:
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.agent.additionalAnnotations }}
{{ toYaml .Values.agent.additionalAnnotations | indent 4 }}
    {{- end }}
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    app: sensor
    app.kubernetes.io/name: sensor
    {{- if .Values.agent.additionalLabels }}
{{ toYaml .Values.agent.additionalLabels | indent 4 }}
    {{- end }}
  name: {{ include "sensor.metric-ingestor-hostname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app.kubernetes.io/name: sensor
    app.kubernetes.io/part-of: '{{ include "groundcover.labels.partOf" . }}'
  ports:
  - protocol: TCP
    name: metric-ingestor
    port: {{ $sensorValues.metricIngestor.serverPort }}
    targetPort: {{ $sensorValues.metricIngestor.serverPort }}
{{- end }}
{{- end }}
