apiVersion: v2
dependencies:
- condition: global.postgresql.enabled
  import-values:
  - child: serviceAccount
    parent: global.postgresql.serviceAccount
  name: postgresql
  repository: https://charts.bitnami.com/bitnami
  version: 12.6.9
- condition: global.workflows.enabled
  name: keep
  repository: https://keephq.github.io/helm-charts
  version: 0.1.67
- condition: global.backend.victoria-metrics-distributed.enabled
  name: victoria-metrics-distributed
  repository: https://victoriametrics.github.io/helm-charts/
  version: 0.11.0
- condition: global.temporal.enabled
  name: temporal
  repository: https://go.temporal.io/helm-charts
  version: 0.35.0
name: backend
type: application
version: 0.0.0
