{{ if .Values.backend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "promscale.fullname" . }}
  namespace: {{ template "promscale.namespace" . }}
  labels:
    app: {{ template "promscale.fullname" . }}
    chart: {{ template "promscale.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: "promscale-connector"
    app.kubernetes.io/part-of: "promscale-connector"
    app.kubernetes.io/component: "connector"
spec:
  replicas: {{ .Values.promscale.replicaCount }}
  strategy:
    type: {{ .Values.promscale.upgradeStrategy }}
  selector:
    matchLabels:
      app: {{ template "promscale.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "promscale.fullname" . }}
        chart: {{ template "promscale.chart" . }}
        release: {{ .Release.Name }}
        app.kubernetes.io/name: "promscale-connector"
        app.kubernetes.io/part-of: "promscale-connector"
        app.kubernetes.io/component: "connector"
      annotations: 
        groundcover_version: {{ .Values.origin.tag }}
        checksum/config: {{ printf "%s" .Values.promscale.connection | sha256sum -}}
        {{- if .Values.promscale.prometheus.annotations }}
        {{- .Values.promscale.prometheus.annotations | toYaml | nindent 8 }}
        {{- end }}
    spec:
{{- if .Values.pullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.pullSecrets | indent 8 }}
{{- end }}
      initContainers:
        - name: check-ts-ready
          image: public.ecr.aws/groundcovercom/postgres:9.6.5
          command:
            - bash
            - -c
            - |
              [ -z "$GROUNDCOVER_VERSION" ] && echo "\$GROUNDCOVER_VERSION is missing" && exit 1
              for i in {1..1800}; do sleep 2; DB_VERSION=`psql -X -A -t -h groundcover-tsdb -U postgres -c "SELECT value FROM version ORDER BY time desc limit 1"`; echo "running_version = '$GROUNDCOVER_VERSION', db_version='$DB_VERSION'"; [[ "$GROUNDCOVER_VERSION" == "$DB_VERSION" ]] && echo "DONE" && exit 0; done; echo "TIMEOUT"; exit 1;
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  key: PATRONI_SUPERUSER_PASSWORD
                  name: {{ index .Values "timescaledb-single" "secrets" "credentialsSecretName" | default "groundcover-tsdb-credentials" }}
            - name: GROUNDCOVER_VERSION
              valueFrom:
                fieldRef:
                  fieldPath: metadata.annotations['groundcover_version']
      containers:
        - image: {{ .Values.origin.registry }}/{{ .Values.promscale.repository }}:{{ .Values.origin.tag }}
          imagePullPolicy: {{ .Values.promscale.imagePullPolicy }}
          name: promscale-connector
          {{- if or (.Values.promscale.openTelemetry.enabled) (.Values.promscale.extraArgs) }}
          args:
          - "--startup.dataset.config=traces:\n  default_retention_period: {{ .Values.agent.alligator.dataRetention }}"
          {{- if .Values.promscale.openTelemetry.enabled }}
          - --tracing.otlp.server-address=:9202
          {{- end }}
          {{- with .Values.promscale.extraArgs }}
          {{ toYaml . | nindent 10 }}
          {{- end }}
          {{- end }}
          env:
            - name: PROMSCALE_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: PATRONI_SUPERUSER_PASSWORD
                  name: {{ index .Values "timescaledb-single" "secrets" "credentialsSecretName" | default "groundcover-tsdb-credentials" }}
          {{- if .Values.promscale.extraEnv }}
            {{- range $.Values.promscale.extraEnv }}
            - name: {{ .name }}
              value: {{ tpl (.value | quote) $ }}
            {{- end }}
          {{- end }}
          envFrom:
          - secretRef:
              {{- $secretName := ternary (include "promscale.fullname" .) .Values.promscale.connectionSecretName (eq .Values.promscale.connectionSecretName "") }}
              name: {{ tpl $secretName . }}
          {{- if .Values.promscale.resources }}
          resources:
            {{- toYaml .Values.promscale.resources | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: 9201
              name: metrics-port
          {{- if .Values.promscale.openTelemetry.enabled }}
            - containerPort: 9202
              name: otel-port
          {{- end }}
          volumeMounts:
          - mountPath: /var/groundcover/server
            name: certificate
            readOnly: true
      volumes:
      - name: certificate
        secret:
          secretName: {{ template "promscale_secrets_certificate" . }}
          defaultMode: 416 # 0640 permissions
      serviceAccountName: {{ template "promscale.fullname" . }}
      {{- with .Values.promscale.nodeSelector }}
      nodeSelector:
      {{ toYaml . | indent 2 }}
      {{- end }}
      {{- with .Values.promscale.tolerations }}
      tolerations: {{ toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.promscale.affinity }}
      affinity: {{ toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
