{{ if .Values.backend.enabled }}
{{- if .Values.promscale.promIngress.enabled -}}
{{- $fullName := printf "%s-connector" (include "promscale.fullname" . | trunc 53) -}}
{{- $svcPort := .Values.promscale.prometheus.port -}}
{{- $apiVersion := include "ingress.apiVersion" . -}}
apiVersion: {{ $apiVersion }}
kind: Ingress
metadata:
  name: {{ $fullName }}-prometheus
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "promscale.fullname" . }}
    chart: {{ template "promscale.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  {{- with .Values.promscale.promIngress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
{{- if .Values.promscale.promIngress.ingressClassName }}
  ingressClassName: {{ .Values.promscale.promIngress.ingressClassName }}
{{- end }}
{{- if .Values.promscale.promIngress.tls }}
  tls:
  {{- range .Values.promscale.promIngress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.promscale.promIngress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
        {{- range .paths }}
          - path: {{ . }}
            {{- if eq $apiVersion "networking.k8s.io/v1" }}
            pathType: Prefix
              {{- end }}
            backend:
              {{- if eq $apiVersion "networking.k8s.io/v1" }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
        {{- end }}
  {{- end }}
{{- end }}
{{- end }}