{{ if .Values.backend.enabled }}
{{ if eq .Values.promscale.connectionSecretName "" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "promscale.fullname" . }}
  namespace: {{ template "promscale.namespace" . }}
  labels:
    {{ with .Values.global.groundcoverLabels }} 
    {{- toYaml . | nindent 4 }}
    {{- end }}
    app: {{ template "promscale.fullname" . }}
    chart: {{ template "promscale.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/name: "promscale-connector"
    app.kubernetes.io/part-of: "promscale-connector"
    app.kubernetes.io/component: "connector"

stringData:
  {{- if ne (.Values.promscale.connection.uri | toString) "" }}
  PROMSCALE_DB_URI: {{ tpl .Values.promscale.connection.uri . | toString | quote }}
  {{- else }}
  PROMSCALE_DB_PORT: {{ .Values.promscale.connection.port | toString | quote }}
  PROMSCALE_DB_USER: {{ .Values.promscale.connection.user | toString | quote }}
  PROMSCALE_DB_PASSWORD: {{ .Values.promscale.connection.password | toString | quote }}
  PROMSCALE_DB_HOST: {{ tpl .Values.promscale.connection.host . | toString | quote }}
  PROMSCALE_DB_NAME: {{ .Values.promscale.connection.dbName | toString | quote }}
  PROMSCALE_DB_SSL_MODE: {{ .Values.promscale.connection.sslMode | toString | quote }}
  {{- end }}
{{ end }}
{{- end }}
