apiVersion: v1
kind: Secret
metadata:
  name: {{ template "promscale_secrets_certificate" $ }}
  labels:
    app: {{ template "promscale.fullname" $ }}
    cluster-name: {{ template "clusterName" $ }}
type: kubernetes.io/tls
{{ $ca := genCA (include "promscale.fullname" .) 1826 -}}
stringData:
  tls.crt: {{ $ca.Cert | quote }}
  tls.key: {{ $ca.Key  | quote }}