apiVersion: v1
kind: ConfigMap
metadata:
  name: metrics-ingester-aggregation-config
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
data:
  aggregation_config.yaml: |
    - match: '{__name__=~"^groundcover_.+_.+_counter$", node_name!=""}'
      without: [node_name]
      interval: 30s
      outputs: [total]
      output_relabel_configs:
      - source_labels: [__name__]
        target_label: __name__
        regex: "(.+):.*"
        replacement: "$1"