{{ if .Values.global.workflows.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keep-credentials
stringData:
{{ $webHookApiKey := include "keep.webhook.apikey" . }}
{{ $adminApiKey := include "keep.admin.apikey" . }}
    api-keys: {{ printf "gc-webhook:webhook:%s,admin:admin:%s" $webHookApiKey $adminApiKey | quote }}
    webhook-key: {{ $webHookApiKey | quote }}
    admin-api-key: {{ $adminApiKey | quote }}
    username: admin
    password: {{ include "keep.admin.password" . | quote }}
{{ end }}