{{ if .Values.global.workflows.enabled }}
apiVersion: v1
data:
  provisionedProviders.json: '{"groundcoverVictoriaMetrics":{"type":"victoriametrics","authentication":{"VMAlertHost":"{{ tpl .Values.keep.backend.provisionedProviders.groundcoverVictoriaMetrics.authentication.vmAlertHost . }}","VMAlertPort":"{{ tpl .Values.keep.backend.provisionedProviders.groundcoverVictoriaMetrics.authentication.vmAlertPort . }}"}},"groundcoverClickhouse":{"type":"clickhouse","authentication":{"host":"{{ tpl .Values.keep.backend.provisionedProviders.groundcoverClickhouse.authentication.host . }}","port":"{{ tpl .Values.keep.backend.provisionedProviders.groundcoverClickhouse.authentication.port . }}","username":"{{ tpl .Values.keep.backend.provisionedProviders.groundcoverClickhouse.authentication.username . }}","password":"$(CLICKHOUSE_PASS)","database":"{{ tpl .Values.keep.backend.provisionedProviders.groundcoverClickhouse.authentication.database . }}"}}}'
kind: ConfigMap
metadata:
  name: keep-config
  namespace: {{ .Release.Namespace }}
{{ end -}}
