{{ if .Values.global.workflows.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: keep-postgres
stringData:
  username: keep
  database: keep
{{ $password := include "keep.postgres.password" . }}
  password: {{ $password | quote }}
  connection_string: {{ printf "postgresql://keep:%s@%s/keep" $password (include "postgresql.base.url" . ) | quote }}
{{ end }}