{{ if and (not (empty .Values.vector.objectStorage.s3Bucket)) (.Values.vector.objectStorage.allowed) (not (empty .Values.vector.objectStorage.accessKey))  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vector.s3.secretName" . }}
  annotations:
    helm.sh/resource-policy: "keep"
type: Opaque
stringData:
  {{ template "vector.s3.secretKey" . }}: {{ .Values.vector.objectStorage.accessKeySecret | quote }}
  {{ template "vector.s3.accessKey" . }}: {{ .Values.vector.objectStorage.accessKey | quote }}
{{ end }}
