{{ if and .Values.global.fleetmanager.enabled .Values.global.backend.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: fleet-manager
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "groundcover.labels" $ | nindent 4 }}
spec:
  maxUnavailable: {{ .Values.fleetManager.pdb.maxUnavailable }}
  selector:
    matchLabels:
      app: fleet-manager
---
{{- end }}
