{{ if .Values.fleetManager.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "groundcover.labels" . | nindent 4 }}
    {{- if .Values.fleetManager.additionalLabels }}
{{ toYaml .Values.fleetManager.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.fleetManager.serviceAccount }}
    {{- if .Values.fleetManager.serviceAccount.annotations }}
{{ toYaml .Values.fleetManager.serviceAccount.annotations | indent 4 }}
    {{- end }}
    {{- end }}
    {{- if .Values.fleetManager.additionalAnnotations }}
{{ toYaml .Values.fleetManager.additionalAnnotations | indent 4 }}
    {{- end }}
  name: fleet-manager
  namespace: {{ .Release.Namespace }}
{{ end }}