{{ if and .Values.global.fleetmanager.enabled .Values.global.backend.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: fleet-manager
    app.kubernetes.io/name: fleet-manager
    {{- include "groundcover.labels" . | nindent 4 }}
    {{- if .Values.fleetManager.additionalLabels }}
    {{ toYaml .Values.fleetManager.additionalLabels | indent 4 }}
    {{- end }}
  annotations:
    groundcover_version: {{ default .Chart.AppVersion .Values.global.origin.tag }}
    {{- if .Values.fleetManager.additionalAnnotations }}
    {{ toYaml .Values.fleetManager.additionalAnnotations | indent 4 }}
    {{- end }}

  name: {{ .Values.fleetManager.serviceName }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: manage-http
    port: {{ .Values.fleetManager.manageHttpPort }}
    protocol: TCP
    targetPort: manage-http
  selector:
    app: fleet-manager
  type: ClusterIP
{{ end }}